#pragma once

NS_BEGIN(Engine)
NS_BEGIN(SOUND)



enum class SD_KIND {
#pragma region BGM
	BGM_Battle_0,
	BGM_Battle_1,
	BGM_Land_DAY,
	BGM_Land_NIGHT,
	BGM_HOGWART_0,
	BGM_HOGWART_1,
	BGM_HOGWART_INT,
	BGM_RANROK_0,
#pragma endregion
#pragma region SPELL
	SP_JAP_0,
	SP_JAP_1,
	SP_JAP_13,
	SP_BLINK_2,
#pragma endregion
#pragma region AVADA_KEDAVRA
	S_AVADA_KEDAVRA_0,
	S_AVADA_KEDAVRA_1,
	S_AVADA_KEDAVRA_2,
	S_AVADA_KEDAVRA_3,
	S_AVADA_KEDAVRA_4,
	S_AVADA_KEDAVRA_5,
	S_AVADA_KEDAVRA_6,
	S_AVADA_KEDAVRA_7,
	S_AVADA_KEDAVRA_8,
	S_AVADA_KEDAVRA_9,
	S_AVADA_KEDAVRA_10,
	S_AVADA_KEDAVRA_11,
	S_AVADA_KEDAVRA_12,
#pragma endregion

#pragma region ANCIENT_LIGHTNING
	SP_LIGHTNING_0,
	SP_LIGHTNING_1,
	SP_LIGHTNING_2,
	SP_LIGHTNING_3,
#pragma endregion

#pragma region ACCIO
	SP_ACCIO_0,
	SP_ACCIO_1,
	SP_ACCIO_2,
	SP_ACCIO_3,
	SP_ACCIO_4,
	SP_ACCIO_5,
	SP_ACCIO_6,
	SP_ACCIO_7,
	SP_ACCIO_8,
	SP_ACCIO_9,
	SP_ACCIO_10,
	SP_ACCIO_11,
	SP_ACCIO_12,
	SP_ACCIO_13,
	SP_ACCIO_14,
	SP_ACCIO_15,
	SP_ACCIO_16,
	SP_ACCIO_17,
	SP_ACCIO_18,
	SP_ACCIO_19,
	SP_ACCIO_20,
	SP_ACCIO_21,
	SP_ACCIO_22,
	SP_ACCIO_23,

#pragma endregion

#pragma region REPARO
	SP_REPARO_0,
	SP_REPARO_1,
	SP_REPARO_2,
#pragma endregion

#pragma region DECENDO
	SP_DECENDO_0,
	SP_DECENDO_1,
	SP_DECENDO_2,
	SP_DECENDO_3,
	SP_DECENDO_4,
	SP_DECENDO_5,
	SP_DECENDO_6,
	SP_DECENDO_7,
	SP_DECENDO_8,
	SP_DECENDO_9,
	SP_DECENDO_10,
	SP_DECENDO_11,
	SP_DECENDO_12,
	SP_DECENDO_13,
	SP_DECENDO_14,
	SP_DECENDO_15,
	SP_DECENDO_16,
	SP_DECENDO_17,
	SP_DECENDO_18,
	SP_DECENDO_19,
	SP_DECENDO_20,
	SP_DECENDO_21,
	SP_DECENDO_22,
	SP_DECENDO_23,
	SP_DECENDO_24,
	SP_DECENDO_25,

#pragma endregion

#pragma region BOMBARD
	SP_BOMBARD_0,
	SP_BOMBARD_1,
	SP_BOMBARD_2,
	SP_BOMBARD_3,
	SP_BOMBARD_4,
	SP_BOMBARD_5,
	SP_BOMBARD_6,
	SP_BOMBARD_7,
	SP_BOMBARD_8,
	SP_BOMBARD_9,
	SP_BOMBARD_10,
	SP_BOMBARD_11,
	SP_BOMBARD_12,
	SP_BOMBARD_13,
	SP_BOMBARD_14,
	SP_BOMBARD_15,
	SP_BOMBARD_16,
	SP_BOMBARD_17,
	SP_BOMBARD_18,
	SP_BOMBARD_19,
	SP_BOMBARD_20,
	SP_BOMBARD_21,
	SP_BOMBARD_22,
	SP_BOMBARD_23,
	SP_BOMBARD_24,
	SP_BOMBARD_25,
	SP_BOMBARD_26,
	SP_BOMBARD_27,
	SP_BOMBARD_28,
	SP_BOMBARD_29,
	SP_BOMBARD_30,
	SP_BOMBARD_31,
	SP_BOMBARD_32,
	SP_BOMBARD_33,
	SP_BOMBARD_34,
	SP_BOMBARD_35,
	SP_BOMBARD_36,
	SP_BOMBARD_37,
	SP_BOMBARD_38,
	SP_BOMBARD_39,
	SP_BOMBARD_40,
	SP_BOMBARD_41,
	SP_BOMBARD_42,
	SP_BOMBARD_43,
	SP_BOMBARD_44,
	SP_BOMBARD_45,
	SP_BOMBARD_46,
#pragma endregion

#pragma region LEVIOSA

	SP_LEVIOSA_0,
	SP_LEVIOSA_1,
	SP_LEVIOSA_2,
	SP_LEVIOSA_3,
	SP_LEVIOSA_4,
	SP_LEVIOSA_5,
	SP_LEVIOSA_6,
	SP_LEVIOSA_7,
	SP_LEVIOSA_8,
	SP_LEVIOSA_9,
	SP_LEVIOSA_10,
	SP_LEVIOSA_11,
	SP_LEVIOSA_12,
	SP_LEVIOSA_13,
	SP_LEVIOSA_14,
	SP_LEVIOSA_15,
	SP_LEVIOSA_16,
	SP_LEVIOSA_17,
	SP_LEVIOSA_18,
	SP_LEVIOSA_19,
	SP_LEVIOSA_20,
	SP_LEVIOSA_21,
	SP_LEVIOSA_22,
	SP_LEVIOSA_23,
	SP_LEVIOSA_24,
	SP_LEVIOSA_25,
	SP_LEVIOSA_26,
	SP_LEVIOSA_27,

#pragma endregion


#pragma region PROTEGO

	SP_PROTEGO_0,
	SP_PROTEGO_1,
	SP_PROTEGO_2,
	SP_PROTEGO_3,
	SP_PROTEGO_4,
	SP_PROTEGO_5,
	SP_PROTEGO_6,
	SP_PROTEGO_7,
	SP_PROTEGO_8,
	SP_PROTEGO_9,
	SP_PROTEGO_10,
	SP_PROTEGO_11,
	SP_PROTEGO_12,
	SP_PROTEGO_13,
	SP_PROTEGO_14,
	SP_PROTEGO_15,
	SP_PROTEGO_16,
	SP_PROTEGO_17,
	SP_PROTEGO_18,
	SP_PROTEGO_19,
	SP_PROTEGO_20,
	SP_PROTEGO_21,
	SP_PROTEGO_22,
	SP_PROTEGO_23,
	SP_PROTEGO_24,
	SP_PROTEGO_25,
	SP_PROTEGO_26,
	SP_PROTEGO_27,
	SP_PROTEGO_28,
	SP_PROTEGO_29,
	SP_PROTEGO_30,


#pragma endregion




#pragma region LUMOS
	SP_LUMOS_0,
	SP_LUMOS_1,
#pragma endregion

#pragma region VOICE
	VOICE_AVADAKEDAVRA,
	VOICE_BOMBARDA,
	VOICE_DECENDO,
	VOICE_LEVIOSO,
	VOICE_LUMOS,
	VOICE_PROTEGO,
	VOICE_REPARO,
	VOICE_REVELIO,
	VOICE_STUPEFY,
#pragma endregion

#pragma region BROOM
	BROOM_BOOST,
	BROOM_DOWN,
	BROOM_GET_ITEM,
	BROOM_NORMAL,
	BROOM_RIDE,
#pragma endregion

#pragma region DOOR
	DOOR_OPEN,
	DOOR_CLOSE,
#pragma endregion

#pragma region CHEST
	CHEST_FOUND,
	CHEST_OPEN,
#pragma endregion

	END,
};

constexpr size_t SD_KIND_COUNT = static_cast<size_t>(SD_KIND::END);

struct ENGINE_DLL SD_PATH final {
	static const _tchar* const SD_KIND_PATHS[SD_KIND_COUNT];
};


NS_END // NS_SOUND
NS_END // NS_Engine
