#pragma once

NS_BEGIN(Engine)
NS_BEGIN(SOUND)


enum class SD_CHANNEL_GROUP {
	BGM,
	ENVIRONMENT,
	EFFECT,
	VOICE,
	END
};

enum class SD_KIND {
#pragma region BGM
	BGM_0,
	BGM_1,
#pragma endregion
#pragma region SPELL
	SP_JAP_0,
	SP_JAP_1,
	SP_JAP_13,
	SP_BLINK_2,
#pragma endregion
#pragma region AVADA_KEDAVRA
	S_AVADA_KEDAVRA_0,
	S_AVADA_KEDAVRA_1,
	S_AVADA_KEDAVRA_2,
	S_AVADA_KEDAVRA_3,
	S_AVADA_KEDAVRA_4,
	S_AVADA_KEDAVRA_5,
	S_AVADA_KEDAVRA_6,
	S_AVADA_KEDAVRA_7,
	S_AVADA_KEDAVRA_8,
	S_AVADA_KEDAVRA_9,
	S_AVADA_KEDAVRA_10,
	S_AVADA_KEDAVRA_11,
	S_AVADA_KEDAVRA_12,
#pragma endregion
#pragma region ACCIO
	SP_ACCIO_0,
	SP_ACCIO_1,
	SP_ACCIO_2,
	SP_ACCIO_3,
	SP_ACCIO_4,
	SP_ACCIO_5,
	SP_ACCIO_6,
#pragma endregion


#pragma region VOICE
	VOICE_AVADAKEDAVRA,
	VOICE_BOMBARDA,
	VOICE_DECENDO,
	VOICE_LEVIOSO,
	VOICE_LUMOS,
	VOICE_PROTEGO,
	VOICE_REPARO,
	VOICE_REVELIO,
	VOICE_STUPEFY,
#pragma endregion
	END,
};

constexpr size_t SD_KIND_COUNT = static_cast<size_t>(SD_KIND::END);

struct ENGINE_DLL SD_PATH final {
	static const _tchar* const SD_KIND_PATHS[SD_KIND_COUNT];
};


NS_END // NS_SOUND
NS_END // NS_Engine
