#pragma once
#include "Base.h"

NS_BEGIN(STATEANIM)
enum ESTATE
{
    IDLE, IDLE_G,IDLE_AIM, IDLE_TURN_L, IDLE_TURN_R, IDLE_TURN_BWD, IDLE_COMBAT_TURN_BWD_L, IDLE_COMBAT_TURN_BWD_R, IDLE_COMBAT_TURN_90_L, IDLE_COMBAT_TURN_90_R,IDLE_BREAK1,IDLE_BREAK2,IDLE_BREAK3,IDLE_BREAK4, IDLE_BREAK5, IDLE_BREAK6, IDLE_BREAK7,
    MOVE, 
    WALK, WALK_FWD,WALK_RIGHT,WALK_LEFT, WALK_BWD,WALK_START,WALK_STOP,
	JOG,JOG_START, JOG_FWD, JOG_RIGHT, JOG_LEFT, JOG_BWD, JOG_STOP, JOG_AIM_LEFT, JOG_AIM_RIGHT, JOG_AIM_BWD, JOG_AIM_STOP_L, JOG_AIM_STOP_R, JOG_AIM_STOP_BWD,JOG_LEFT_TURN,JOG_RIGHT_TURN,JOG_112_L,JOG_112_R,JOG_90_L,JOG_90_R,
    SPRINT,
    SLIDE_START_R,SLIDE_LOOP_R,SLIDE_STOP_R,
    JUMP,JUMP_JOG,JUMP_SPRINT,FALL_LOOP,
    LAND,LAND_TO_JOG,LAND_TO_SPRINT,
    DODGE,DODGE_BLINK, DODGE_LEFT, DODGE_RIGHT,
    COMBAT, SKILL, SKILL2,
    SPELL, SPELL_180_R, SPELL_90_L,
    LIGHT_ATTACK,LIGHT_ATTACK_180_R, LIGHT_ATTACK_90_L, LIGHT_ATTACK_90_R1, LIGHT_ATTACK_90_R2, LIGHT_ATTACK_90_R3,
    ATTACK_END,
    SHUFFLE1, SHUFFLE2, SHUFFLE3, SHUFFLE4,
    MAPHELP,POTION,
    ACCIO,DESCENDO,DIFFINDO,DEPULSO,LUMOS,LUMOS_STOP,DISILLUSION_ENTER,DISILLUSION_EXIT, ANCIENT_THROW,
    SPELL_FAIL, SPELL_CHARGE,
    ANCIENT_LIGHTNING_CHARGE, ANCIENT_LIGHTNING,
    PARRY_180,PARRY2, PARRY3, PARRY4,
    BROOM_IDLE,BROOM_FWD,BROOM_LEFT,BROOM_RIGHT,BROOM_DOWN,BROOM_UP, BROOM_REVELIO, BROOM_HOVER_IDLE, BROOM_HOVER_FWD, BROOM_HOVER_LEFT, BROOM_HOVER_RIGHT, BROOM_HOVER_START, BROOM_HOVER_REVELIO,BROOM_MOUNT, BROOM_MOUNT_END,BROOM_DISMOUNT,BROOM_TURBO_FWD, BROOM_TURBO_DOWN, BROOM_TURBO_UP, BROOM_TURBO_LEFT, BROOM_TURBO_RIGHT,
    RUSH_START,RUSH_LOOP,RUSH_END,
    THROW_ROCK_START,THROW_ROCK,
    BACKHAND_SWING_JOG,SWING_FWD,SLAM,
    SUSTAIN_START,SUSTAIN_LOOP,SUSTAIN_END,
    BLINK,BLINK_START,
    HIT, HIT_FWD, HIT_BWD, HIT_BWD2, HIT_BWD3, HIT_BWD4, HIT_L, HIT_R,HIT_FACE,HIT_FACE_END,HIT_LEVIOSO,INCARCEROUS,
    KNOCKDOWN, KNOCKDOWN_FWD, KNOCKDOWN_FWD_SPLT, KNOCKDOWN_FWD_SPLT_HOLD, KNOCKDOWN_BWD, KNOCKDOWN_BWD_SPLT, KNOCKDOWN_BWD_SPLT_HOLD,
    GETUP, GETUP_BWD, GETUP_FWD, GETUP_L, GETUP_L_FD, GETUP_L_FU, GETUP_R, GETUP_R_FD, GETUP_R_FU, GETUP_SLOUCH,
    DEAD, DEAD_FWD, DEAD_FWD2, DEAD_BWD, DEAD_BWD2, DEAD_L, DEAD_L2, DEAD_R, DEAD_R2,
    KNOCKBACK, KNOCKBACK2,
    TUMBLE, TUMBLE2,TUMBLE_FWD,
    PETRIFICUSED_START,
    STUN,
    FLINCH_BWD,FLINCH_FWD, FLINCH_LEFT, FLINCH_RIGHT,
    STUMBLE_BWD_L,STUMBLE_BWD_R,STUMBLE_FWD,
    HOVER_LOOP,HOVER_DASH_FWD, HOVER_DASH_BWD, HOVER_DASH_LEFT, HOVER_DASH_RIGHT,
    FIREBALL1_A,FIREBALL2_A, FIREBALL1_G, FIREBALL2_G,
    FIREBREATH_A,FIREBREATH_COOLDOWN_A,FIREBREATH_WINDUP_A, FIRESWEEP_A, FIRESWEEP_COOLDOWN_A, FIRESWEEP_WINDUP_A, FIREBREATH_G, FIRESWEEP_G,
    PULSE,
    GROUND_SWIPE_L,GROUND_SWIPE_R,
    TUCKED,FLY_TO_HOVER,
    FIREBURST_REEL,
    ////////////////////////// 빗자루
    BROOM_MOUNT_B, BROOM_HOVER_IDLE_B, BROOM_HOVER_STOP_B,BROOM_HOVER_DOWN_B,BROOM_HOVER_UP_B,BROOM_HOVER_LEFT_B,BROOM_HOVER_RIGHT_B,BROOM_FLY_DOWN_B, BROOM_FLY_LEFT_B, BROOM_FLY_RIGHT_B, BROOM_FLY_UP_B,BROOM_FLY_B,BROOM_ADD,
    /// ////////////////////////////
    END
};
NS_END

NS_BEGIN(Engine)
class CUnit;
class CModel;
class CFSM;
class CGameInstance;

class ENGINE_DLL CState abstract : public CBase
{
protected:
    typedef struct tagStateDesc {
        class CUnit* pOwner = { nullptr };
    }STATEDESC;

protected:
    CState();
    virtual ~CState() = default;

public:
    virtual void Enter()PURE;
    virtual HRESULT Update(_float fTimeDelta)PURE;
    virtual void Exit()PURE;

protected:
    class CUnit*              m_pOwner = { nullptr };
    CModel*             m_pModel = { nullptr };
    CFSM*               m_pFSM = { nullptr };
    CGameInstance*      m_pGameInstance = { nullptr };

protected:
    HRESULT Initialize(STATEDESC* pArg);

protected:
    virtual void Free() override;
    virtual void Describe_Entity();
};

NS_END
