#pragma once

#include <process.h>
#include "../Default/framework.h"
#include "wincrypt.h"

#include "Engine_Define.h"
#include "Editor_Macro.h"
#include "Editor_Struct.h"

namespace Editor
{
	const unsigned int			g_iWinSizeX = 1920;
	const unsigned int			g_iWinSizeY = 1080;

	enum class LEVEL { STATIC, LOADING, LOGO, LOBY, GAMEPLAY, RESTART, OBJECT, MAP, UI, EFFECT, PHYSX, BLOOM, END };
	enum class COLLIDABLEOBJECT { PLAYER, MONSTER, HOSTILE_HITBOX, ALLY_HITBOX, NEUTRAL_HITBOX, ENVIRIONMENT, NPC, ITEM, TRIGGERBOX, REGION, NOCOLLIDE, END };
	enum class MAPOBJECT_TYPE { CONTAINER, ELEMENT_STATIC, ELEMENT_INTERACT, ELEMENT_LIGHT, ELEMENT_LAKE };
	enum class MAPOBJECT_RENDER_TYPE { NORMAL, DECAL, GLASS };

	enum class SHADER_PASS_ANIM { DEFAULT, SHADOW, CAPTURE, BLUR, HAIR, EYELASH, OUTLINE_WRITE, OUTLINE_READ, SPECTOR, END };
	enum class SHADER_PASS_NPC_PBR_ANIM {
		EYELASH_DAOTHV_ToSRO, TEETH_SRXO_ToSRO, EYE_DN_ToSRO, EYE_OCC, FACIAL_HAIR_DAOTHV_ToSRO, HEAD_HAIR_DAOTHV_ToSRO, HEADwtHAND_DSRXON_ToSRO, LOWER_DSRON_ToSRO, UPPER_DMRON_ToMRO, GLASSES_DMRON_ToMRO, EmissiveMetalness_DENMRO_ToMRO, MI_ClothSim_DSEN_ToSRO, MI_Troll_Club_DAENMROSRXO_To
		, OUTLINE_READ, TEETH_SRXO_ToSRO__OUTLINE_WRITE, EYE_DN_ToSRO__OUTLINE_WRITE, HEADwtHAND_DSRXON_ToSRO__OUTLINE_WRITE, UPPER_DMRON_ToMRO__OUTLINE_WRITE, EmissiveMetalness_DENMRO_ToMRO__OUTLINE_WRITE, MI_ClothSim_DSEN_ToSRO__OUTLINE_WRITE
		, END
	};
	enum class SHADER_PASS_MESH { DEFAULT, SHADOW, SKYBOX, ALPHABLEND, EFFECT_ALPHABLEND, EFFECT_BLEND, EFFECT_ALPHABLEND_CULL, EFFECT_BLEND_CULL, CAPTURE, BLUR, EFFECT_ALPHABLEND_UVMOVE, MAPTOOL, GLASS, OUTLINE_WRITE, OUTLINE_READ, BLOOM, LAKE, END };
	enum class SHADER_PASS_NORTEX { DEFAULT, TERRAIN, ENV_TERRAIN_ANISO, SHADOW, END };
	enum class SHADER_PASS_PARTICLE { EXPLOSION, END };


	enum class SHADER_PASS_POSTEX { DEFAULT, SCISSOR, UI, UVMOVE, TRAIL, TRAIL_BLEND, TRAILWB_FOR_BLEND, TRAIL_BLUR, TRAIL_BLOOM, END };
	enum class SHADER_PASS_UIEDITOR {
		DEFAULT, COLOR, LOGO, LOGO_TEXT, LOGO_GLOW, ALPHABLEND, CLAMP, CURSOR,
		LODING, HOLD_ROTATION, MISSION, QUESTTYPE, UVMULT, NINECLICE,
		ROTATION, SLOT, TYPE, HPBAR, MAGIC_METER, MAGIC_ICON, REMOVEUV,
		REVELIO, POTION, MAGIC_ITEM, SPELL_PREVIEW, SPELL_HEADER,
		SPELL_HEADER_LINE, SPELL_DRAG, CAMERA_LOCKON, LODING_SCREEN,
		ENEMY_HPBAR, BOSS_HPBAR, QUEST_BORDER, QUEST_INFO, QUEST_STATUS, BROOMSTICK,
		SPELL_LEARN, SPELLLEARNCOLOR, SPELLLEARNBOOSTER, NPCINTERACTION, CANVASFADE,
		FLAGWAVE, BROOMCIRCLE, RIDE_INFO_KEY, RIDE_INFO, RIDE_HPSLOT, BOOSTERGAUGE,
		BOOSTERHPBAR,	
		ENEMY_DETECTION, INTERACTION_OBJECT, INTERACTION_NPC, BROOMTARGETGATE, END
	};
	enum class SHADER_PASS_INSTANCE_MODEL { DEFAULT, NON_NOMALMAP, BLUR, WEIGHTBLEND, NON_WORLD, NON_WORLD_BLUR, BLEND, BLEND_NOWORLD, BLOOM, BLOOM_NOWORLD, BLUR_NO_EMMISVE, BLUR_NO_WORLD_NO_EMISSIVE, WEIGHTBLEND_FOR_BLEND, DEPTH_STOP, WB_CULLING, SCREEN_FX , DISTORTION , NONPOS , NONPOS_BLUR, BLUR_MESH, BLUR_CULLING , BLUR_CULLING_NO_EMISSIVE, BLOOM_CULLING , DEFAULT_NONPOS , NONWB_NONPOS, DECAL, DECAL_WB, DECAL_BLUR, BLEND_CULLING,  END};

	enum class SHADER_PASS_UIINTANCE { DEFAULT, ALPHABLEND, UVALPHABLEND, MAGIC_METER, SPELL_LIST, EESSENTIAL_SPELL_SOLT, EESSENTIAL_SPELL, COLOR, SPELL_HOVER, SPELL_SLOT_EFFECT, SPELL_SLOT, SPELL_LOCK, QUEST_SLOT, END };

	enum class QUESTTYPE { MAIN, SUB, END };
	enum class QUESTSTATE { NONE, ACCEPTED, CLEARED };
	enum class EFFECT_TYPE { EFFECT, TRAIL, END };
	enum class SKILL_TYPE {
		ARRESTO_MOMENTUM, GLACIUS, LEVIOSO, TRANSFORM,	// 노란색
		ACCIO, DEPULSO, DESCENDO, FLIPENDO,										// 보라색
		CONFRINGO, DIFFINDO, EXPELLIARMUS, BOMBARDA, INCENDIO,					// 빨간색
		DISILLUSIONMENT, LUMOS, REPARO, WINGARDIUM_LEVIOSA,						// 하늘색
		CONJURING_SPELL, ALTERING_SPELL, EVANESCO,								// 연녹색
		AVADAKEDAVRA, CRUCIO, IMPERIO,											// 진녹색
		BEAST_PETTING_BRUSH, BEAST_FEED, NAB_SACK,								// 하늘색
		JAP, REVELIO, PROTEGO, STUPEFY,										// 검은색
		ANCIENT_MAGIC_THROW, ANCIENT_MAGIC, ALOHOMORA, PETRIFICUS_TOTALUS,
		JAP_SIDE, BOMBARDA_SIDE, DESCENDO_SIDE, LEVIOSO_SIDE,

		STUN,
		TROLL_ATTACK, TROLL_RUSH_HIT, TROLL_NOMAL_SMOKE, BLINK, RANROK_FIREBALL, RANROK_BREATH, RANROK_POINT, RANROK_PURSE, RANROK_CHARGE, RANROK_IMPACT , RANROK_HIT, 
		END
	};

	enum class SPELL_LINE { LINE, CURVE };

	enum class BLOOM_TYPE { NONE, BASIC, MULTIPLY, END };

	enum class ELEMENT_INTERACTABLE_ID { BARREL, BOX, END };
}

using namespace Editor;

extern HINSTANCE g_hInstance;
extern HWND g_hWnd;
extern float g_fTimeMult;
