#pragma once

#include <process.h>
#include "../Default/framework.h"
#include "wincrypt.h"

#include "Engine_Define.h"
#include "Editor_Macro.h"
#include "Editor_Struct.h"

namespace Editor
{
	const unsigned int			g_iWinSizeX = 1920;
	const unsigned int			g_iWinSizeY = 1080;

	enum class LEVEL { STATIC, LOADING, LOGO, LOBY, GAMEPLAY, RESTART, OBJECT, MAP, UI, EFFECT, PHYSX, BLOOM, END };
	enum class COLLIDABLEOBJECT { PLAYER, MONSTER, HOSTILE_HITBOX, ALLY_HITBOX, NEUTRAL_HITBOX, ENVIRIONMENT, NPC, ITEM, TRIGGERBOX, REGION, NOCOLLIDE, END };
	enum class MAPOBJECT_TYPE { CONTAINER, ELEMENT_STATIC, ELEMENT_INTERACT };
	enum class MAPOBJECT_RENDER_TYPE {NORMAL, DECAL, GLASS};

	enum class SHADER_PASS_ANIM { DEFAULT, SHADOW, CAPTURE, BLUR, HAIR, EYELASH, OUTLINE_WRITE, OUTLINE_READ, END };
	enum class SHADER_PASS_CUBE { DEFAULT, SHADOW, BLUR, END };
	enum class SHADER_PASS_MESH { DEFAULT, SHADOW, SKYBOX, ALPHABLEND, EFFECT_ALPHABLEND, EFFECT_BLEND, EFFECT_ALPHABLEND_CULL, EFFECT_BLEND_CULL, CAPTURE, BLUR, EFFECT_ALPHABLEND_UVMOVE, MAPTOOL, GLASS, OUTLINE_WRITE, OUTLINE_READ, END };
	enum class SHADER_PASS_NORTEX { DEFAULT, TERRAIN, END };
	enum class SHADER_PASS_PARTICLE { EXPLOSION, END };

	enum class SHADER_PASS_POSTEX { DEFAULT, SCISSOR, UI, UVMOVE, TRAIL, TRAIL_BLUR , TRAIL_BLOOM, END };
	enum class SHADER_PASS_INSTANCE_MODEL { DEFAULT, NON_NOMALMAP, BLUR, WEIGHTBLEND, NON_WORLD, NON_WORLD_BLUR, ALPHA_BLEND, BLOOM, END };
	enum class SHADER_PASS_UIEDITOR { DEFAULT, ALPHABLEND, CLAMP, CURSOR, LODING, HOLD_ROTATION, MISSION, QUESTYPE, UVMULT, NINECLICE, ROTATION, SLOT, SPELLTYPE, HPBAR, MAGIC_METER, MAGIC_ICON, REMOVEUV, REVELIO, POTION, MAGIC_ITEM, END };
	enum class SHADER_PASS_UIINTANCE { DEFAULT, ALPHABLEND, MAGIC_METER, END };

	enum class EFFECT_TYPE { EFFECT, TRAIL, END };
	enum class SKILL_TYPE{ JAP , BOMBARD , DECENDO , PROTEGO , END  };
	enum class BLOOM_TYPE { NONE , BASIC , MULTIPLY , END};
}

using namespace Editor;

extern HINSTANCE g_hInstance;
extern HWND g_hWnd;
extern float g_fTimeMult;
