#include "pch.h"
#include "Engine_Define.h"
#include "SoundSrc.h"


using namespace Engine::SOUND;

const _tchar* const SD_PATH::SD_KIND_PATHS[SD_KIND_COUNT] = {
#pragma region BGM
	TEXT("BGM/battle_BGM_0.wav"), 
	TEXT("BGM/battle_BGM_1.wav"), 
	TEXT("BGM/grassland_day.wav"), 
	TEXT("BGM/grassland_night.wav"), 
	TEXT("BGM/hogwart_BGM_0.wav"), 
	TEXT("BGM/hogwart_BGM_1.wav"), 
	TEXT("BGM/hogwart_BGM_int.wav"), 
	TEXT("BGM/Ranrok_BGM.wav"), 
	TEXT("BGM/InsideBGM.wav"),
	TEXT("BGM/RaceBGM.wav"),
#pragma endregion

#pragma region FOOTSTEP
	TEXT("Player/footsteps/step_int.wav"),
	TEXT("Player/footsteps/step_road.wav"),
	TEXT("Player/footsteps/step_rock.wav"),
	TEXT("Player/footsteps/step_terrain.wav"),
#pragma endregion

#pragma region POTION
	TEXT("Potion/Potion.wav"),
	TEXT("Potion/Potion_broken.wav"),
#pragma endregion
#pragma region ZAP
		TEXT("Player/Zap/ZapHit0.wav"),
		TEXT("Player/Zap/ZapHit1.wav"),
		TEXT("Player/Zap/ZapHit2.wav"),
		TEXT("Player/Zap/ZapHit3.wav"),
#pragma endregion

#pragma region SPELL
	TEXT("Player/spells_jap_akb/jap_0.wav"), 
	TEXT("Player/spells_jap_akb/jap_1.wav"),
	TEXT("Player/spells_jap_akb/jap_13.wav"),
	TEXT("Player/spells_jap_akb/jap_34.wav"),
	TEXT("Player/spells_jap_akb/jap_35.wav"),
	TEXT("Player/spells_jap_akb/jap_36.wav"),
	TEXT("Player/spells_jap_akb/jap_37.wav"),
	TEXT("Player/spells_perk_shadowblink_akb/blink_2.wav"),
#pragma endregion

#pragma region AVADA_KEDAVRA
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_0.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_1.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_2.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_3.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_4.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_5.wav"), // 5
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_6.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_7.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_8.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_9.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_10.wav"), // 10
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_11.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_12.wav"),
#pragma endregion

#pragma region ANCIENT_LIGHTNING
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_0.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_1.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_2.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_3.wav"),
#pragma endregion

#pragma region ACCIO

	TEXT("Player/spells_accio_akb/accio_0.wav"),
	TEXT("Player/spells_accio_akb/accio_1.wav"),
	TEXT("Player/spells_accio_akb/accio_2.wav"),
	TEXT("Player/spells_accio_akb/accio_3.wav"),
	TEXT("Player/spells_accio_akb/accio_4.wav"),
	TEXT("Player/spells_accio_akb/accio_5.wav"),
	TEXT("Player/spells_accio_akb/accio_6.wav"),
	TEXT("Player/spells_accio_akb/accio_7.wav"),
	TEXT("Player/spells_accio_akb/accio_8.wav"),
	TEXT("Player/spells_accio_akb/accio_9.wav"),
	TEXT("Player/spells_accio_akb/accio_10.wav"),
	TEXT("Player/spells_accio_akb/accio_11.wav"),
	TEXT("Player/spells_accio_akb/accio_12.wav"),
	TEXT("Player/spells_accio_akb/accio_13.wav"),
	TEXT("Player/spells_accio_akb/accio_14.wav"),
	TEXT("Player/spells_accio_akb/accio_15.wav"),
	TEXT("Player/spells_accio_akb/accio_16.wav"),
	TEXT("Player/spells_accio_akb/accio_17.wav"),
	TEXT("Player/spells_accio_akb/accio_18.wav"),
	TEXT("Player/spells_accio_akb/accio_19.wav"),
	TEXT("Player/spells_accio_akb/accio_20.wav"),
	TEXT("Player/spells_accio_akb/accio_21.wav"),
	TEXT("Player/spells_accio_akb/accio_22.wav"),
	TEXT("Player/spells_accio_akb/accio_23.wav"),

#pragma endregion

#pragma region REPARO
	TEXT("Player/spells_reparo_akb/reparo_0.wav"),
	TEXT("Player/spells_reparo_akb/reparo_11.wav"),
	TEXT("Player/spells_reparo_akb/reparo_21.wav"),
#pragma endregion

#pragma region DECENDO

	TEXT("Player/spells_descendo_akb/descendo_0.wav"),
	TEXT("Player/spells_descendo_akb/descendo_1.wav"),
	TEXT("Player/spells_descendo_akb/descendo_2.wav"),
	TEXT("Player/spells_descendo_akb/descendo_3.wav"),
	TEXT("Player/spells_descendo_akb/descendo_4.wav"),
	TEXT("Player/spells_descendo_akb/descendo_5.wav"),
	TEXT("Player/spells_descendo_akb/descendo_6.wav"),
	TEXT("Player/spells_descendo_akb/descendo_7.wav"),
	TEXT("Player/spells_descendo_akb/descendo_8.wav"),
	TEXT("Player/spells_descendo_akb/descendo_9.wav"),
	TEXT("Player/spells_descendo_akb/descendo_10.wav"),
	TEXT("Player/spells_descendo_akb/descendo_11.wav"),
	TEXT("Player/spells_descendo_akb/descendo_12.wav"),
	TEXT("Player/spells_descendo_akb/descendo_13.wav"),
	TEXT("Player/spells_descendo_akb/descendo_14.wav"),
	TEXT("Player/spells_descendo_akb/descendo_15.wav"),
	TEXT("Player/spells_descendo_akb/descendo_16.wav"),
	TEXT("Player/spells_descendo_akb/descendo_17.wav"),
	TEXT("Player/spells_descendo_akb/descendo_18.wav"),
	TEXT("Player/spells_descendo_akb/descendo_19.wav"),
	TEXT("Player/spells_descendo_akb/descendo_20.wav"),
	TEXT("Player/spells_descendo_akb/descendo_21.wav"),
	TEXT("Player/spells_descendo_akb/descendo_22.wav"),
	TEXT("Player/spells_descendo_akb/descendo_23.wav"),
	TEXT("Player/spells_descendo_akb/descendo_24.wav"),
	TEXT("Player/spells_descendo_akb/descendo_25.wav"),

#pragma endregion


#pragma region BOMBARD

	TEXT("Player/spells_bombard_akb/bombard_0.wav"),
	TEXT("Player/spells_bombard_akb/bombard_1.wav"),
	TEXT("Player/spells_bombard_akb/bombard_2.wav"),
	TEXT("Player/spells_bombard_akb/bombard_3.wav"),
	TEXT("Player/spells_bombard_akb/bombard_4.wav"),
	TEXT("Player/spells_bombard_akb/bombard_5.wav"),
	TEXT("Player/spells_bombard_akb/bombard_6.wav"),
	TEXT("Player/spells_bombard_akb/bombard_7.wav"),
	TEXT("Player/spells_bombard_akb/bombard_8.wav"),
	TEXT("Player/spells_bombard_akb/bombard_9.wav"),
	TEXT("Player/spells_bombard_akb/bombard_10.wav"),
	TEXT("Player/spells_bombard_akb/bombard_11.wav"),
	TEXT("Player/spells_bombard_akb/bombard_12.wav"),
	TEXT("Player/spells_bombard_akb/bombard_13.wav"),
	TEXT("Player/spells_bombard_akb/bombard_14.wav"),
	TEXT("Player/spells_bombard_akb/bombard_15.wav"),
	TEXT("Player/spells_bombard_akb/bombard_16.wav"),
	TEXT("Player/spells_bombard_akb/bombard_17.wav"),
	TEXT("Player/spells_bombard_akb/bombard_18.wav"),
	TEXT("Player/spells_bombard_akb/bombard_19.wav"),
	TEXT("Player/spells_bombard_akb/bombard_20.wav"),
	TEXT("Player/spells_bombard_akb/bombard_21.wav"),
	TEXT("Player/spells_bombard_akb/bombard_22.wav"),
	TEXT("Player/spells_bombard_akb/bombard_23.wav"),
	TEXT("Player/spells_bombard_akb/bombard_24.wav"),
	TEXT("Player/spells_bombard_akb/bombard_25.wav"),
	TEXT("Player/spells_bombard_akb/bombard_26.wav"),
	TEXT("Player/spells_bombard_akb/bombard_27.wav"),
	TEXT("Player/spells_bombard_akb/bombard_28.wav"),
	TEXT("Player/spells_bombard_akb/bombard_29.wav"),
	TEXT("Player/spells_bombard_akb/bombard_30.wav"),
	TEXT("Player/spells_bombard_akb/bombard_31.wav"),
	TEXT("Player/spells_bombard_akb/bombard_32.wav"),
	TEXT("Player/spells_bombard_akb/bombard_33.wav"),
	TEXT("Player/spells_bombard_akb/bombard_34.wav"),
	TEXT("Player/spells_bombard_akb/bombard_35.wav"),
	TEXT("Player/spells_bombard_akb/bombard_36.wav"),
	TEXT("Player/spells_bombard_akb/bombard_37.wav"),
	TEXT("Player/spells_bombard_akb/bombard_38.wav"),
	TEXT("Player/spells_bombard_akb/bombard_39.wav"),
	TEXT("Player/spells_bombard_akb/bombard_40.wav"),
	TEXT("Player/spells_bombard_akb/bombard_41.wav"),
	TEXT("Player/spells_bombard_akb/bombard_42.wav"),
	TEXT("Player/spells_bombard_akb/bombard_43.wav"),
	TEXT("Player/spells_bombard_akb/bombard_44.wav"),
	TEXT("Player/spells_bombard_akb/bombard_45.wav"),
	TEXT("Player/spells_bombard_akb/bombard_46.wav"),
#pragma endregion

#pragma region LEVIOSA
		TEXT("Player/spells_leviosa_akb/leviosa_0.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_1.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_2.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_3.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_4.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_5.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_6.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_7.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_8.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_9.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_10.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_11.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_12.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_13.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_14.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_15.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_16.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_17.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_18.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_19.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_20.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_21.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_22.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_23.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_24.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_25.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_26.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_27.wav"),

#pragma endregion

#pragma region PROTEGO

		TEXT("Player/spells_protego_akb/protego_0.wav"),
		TEXT("Player/spells_protego_akb/protego_1.wav"),
		TEXT("Player/spells_protego_akb/protego_2.wav"),
		TEXT("Player/spells_protego_akb/protego_3.wav"),
		TEXT("Player/spells_protego_akb/protego_4.wav"),
		TEXT("Player/spells_protego_akb/protego_5.wav"),
		TEXT("Player/spells_protego_akb/protego_6.wav"),
		TEXT("Player/spells_protego_akb/protego_7.wav"),
		TEXT("Player/spells_protego_akb/protego_8.wav"),
		TEXT("Player/spells_protego_akb/protego_9.wav"),
		TEXT("Player/spells_protego_akb/protego_10.wav"),
		TEXT("Player/spells_protego_akb/protego_11.wav"),
		TEXT("Player/spells_protego_akb/protego_12.wav"),
		TEXT("Player/spells_protego_akb/protego_13.wav"),
		TEXT("Player/spells_protego_akb/protego_14.wav"),
		TEXT("Player/spells_protego_akb/protego_15.wav"),
		TEXT("Player/spells_protego_akb/protego_16.wav"),
		TEXT("Player/spells_protego_akb/protego_17.wav"),
		TEXT("Player/spells_protego_akb/protego_18.wav"),
		TEXT("Player/spells_protego_akb/protego_19.wav"),
		TEXT("Player/spells_protego_akb/protego_20.wav"),
		TEXT("Player/spells_protego_akb/protego_21.wav"),
		TEXT("Player/spells_protego_akb/protego_22.wav"),
		TEXT("Player/spells_protego_akb/protego_23.wav"),
		TEXT("Player/spells_protego_akb/protego_24.wav"),
		TEXT("Player/spells_protego_akb/protego_25.wav"),
		TEXT("Player/spells_protego_akb/protego_26.wav"),
		TEXT("Player/spells_protego_akb/protego_27.wav"),
		TEXT("Player/spells_protego_akb/protego_28.wav"),
		TEXT("Player/spells_protego_akb/protego_29.wav"),
		TEXT("Player/spells_protego_akb/protego_30.wav"),

#pragma endregion




#pragma region LUMOS
		TEXT("Player/spells_lumos_akb/lumos_0.wav"),
		TEXT("Player/spells_lumos_akb/lumos_1.wav"),
#pragma endregion

#pragma region VOICE
	TEXT("Player/Voice/avadakedavra_voice.wav"),
	TEXT("Player/Voice/bombarda_voice.wav"),
	TEXT("Player/Voice/decendo_voice.wav"),
	TEXT("Player/Voice/levioso_voice.wav"),
	TEXT("Player/Voice/lumos_voice.wav"),
	TEXT("Player/Voice/protego_voice.wav"),
	TEXT("Player/Voice/reparo_voice.wav"),
	TEXT("Player/Voice/revelio.voice.wav"),
	TEXT("Player/Voice/stupefy_voice.wav"),
	TEXT("Troll/troll_voice.wav"),
	TEXT("Troll/troll_voice_2.wav"),
	TEXT("Troll/troll_voice_3.wav"),
	TEXT("Troll/troll_voice_4.wav"),
	
#pragma endregion

#pragma region BROOM
	TEXT("Player/Broom/broom_boost.wav"),
	TEXT("Player/Broom/broom_down.wav"),
	TEXT("Player/Broom/broom_get_item.wav"),
	TEXT("Player/Broom/broom_normal.wav"),
	TEXT("Player/Broom/broom_ride.wav"),

TEXT("Broom/avatar_broom_center.wav"),
TEXT("Broom/avatar_broom_center_1.wav"),
TEXT("Broom/avatar_broom_center_2.wav"),
TEXT("Broom/avatar_broom_center_3.wav"),
TEXT("Broom/avatar_broom_center_4.wav"),
TEXT("Broom/avatar_broom_center_5.wav"),
TEXT("Broom/avatar_broom_center_6.wav"),
TEXT("Broom/avatar_broom_center_7.wav"),
TEXT("Broom/avatar_broom_center_8.wav"),

TEXT("Broom/avatar_broom_down.wav"),
TEXT("Broom/avatar_broom_down_1.wav"),
TEXT("Broom/avatar_broom_down_2.wav"),
TEXT("Broom/avatar_broom_down_3.wav"),
TEXT("Broom/avatar_broom_down_4.wav"),
TEXT("Broom/avatar_broom_down_5.wav"),
TEXT("Broom/avatar_broom_down_6.wav"),
TEXT("Broom/avatar_broom_down_7.wav"),
TEXT("Broom/avatar_broom_down_8.wav"),

TEXT("Broom/avatar_broom_left.wav"),
TEXT("Broom/avatar_broom_left_1.wav"),
TEXT("Broom/avatar_broom_left_2.wav"),
TEXT("Broom/avatar_broom_left_3.wav"),
TEXT("Broom/avatar_broom_left_4.wav"),
TEXT("Broom/avatar_broom_left_5.wav"),
TEXT("Broom/avatar_broom_left_6.wav"),
TEXT("Broom/avatar_broom_left_7.wav"),
TEXT("Broom/avatar_broom_left_8.wav"),

TEXT("Broom/avatar_broom_right.wav"),
TEXT("Broom/avatar_broom_right_1.wav"),
TEXT("Broom/avatar_broom_right_2.wav"),
TEXT("Broom/avatar_broom_right_3.wav"),
TEXT("Broom/avatar_broom_right_4.wav"),
TEXT("Broom/avatar_broom_right_5.wav"),
TEXT("Broom/avatar_broom_right_6.wav"),
TEXT("Broom/avatar_broom_right_7.wav"),
TEXT("Broom/avatar_broom_right_8.wav"),

TEXT("Broom/avatar_broom_up.wav"),
TEXT("Broom/avatar_broom_up_1.wav"),
TEXT("Broom/avatar_broom_up_2.wav"),
TEXT("Broom/avatar_broom_up_3.wav"),
TEXT("Broom/avatar_broom_up_4.wav"),
TEXT("Broom/avatar_broom_up_5.wav"),
TEXT("Broom/avatar_broom_up_6.wav"),
TEXT("Broom/avatar_broom_up_7.wav"),
TEXT("Broom/avatar_broom_up_8.wav"),

TEXT("Broom/broom_center.wav"),
TEXT("Broom/broom_center_1.wav"),
TEXT("Broom/broom_center_2.wav"),
TEXT("Broom/broom_center_3.wav"),
TEXT("Broom/broom_center_4.wav"),
TEXT("Broom/broom_center_5.wav"),
TEXT("Broom/broom_center_6.wav"),
TEXT("Broom/broom_center_7.wav"),
TEXT("Broom/broom_center_8.wav"),

TEXT("Broom/broom_dismount.wav"),
TEXT("Broom/broom_dismount_1.wav"),
TEXT("Broom/broom_dismount_2.wav"),

TEXT("Broom/broom_down.wav"),
TEXT("Broom/broom_down_1.wav"),
TEXT("Broom/broom_down_2.wav"),
TEXT("Broom/broom_down_3.wav"),
TEXT("Broom/broom_down_4.wav"),
TEXT("Broom/broom_down_5.wav"),
TEXT("Broom/broom_down_6.wav"),
TEXT("Broom/broom_down_7.wav"),
TEXT("Broom/broom_down_8.wav"),

TEXT("Broom/broom_flight.wav"),
TEXT("Broom/broom_flight_1.wav"),
TEXT("Broom/broom_flight_2.wav"),
TEXT("Broom/broom_flight_3.wav"),
TEXT("Broom/broom_flight_4.wav"),
TEXT("Broom/broom_flight_5.wav"),

TEXT("Broom/broom_flight_boost_Play.wav"),
TEXT("Broom/broom_flight_boost_Play_1.wav"),
TEXT("Broom/broom_flight_boost_Play_2.wav"),
TEXT("Broom/broom_flight_boost_Play_3.wav"),

TEXT("Broom/broom_flight_ring_boost_Play.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_1.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_2.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_3.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_4.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_5.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_6.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_7.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_8.wav"),
TEXT("Broom/broom_flight_ring_boost_Play_9.wav"),

TEXT("Broom/broom_flight_roll_left_motion_Play.wav"),

TEXT("Broom/broom_flight_roll_Play.wav"),
TEXT("Broom/broom_flight_roll_Play_1.wav"),
TEXT("Broom/broom_flight_roll_Play_2.wav"),
TEXT("Broom/broom_flight_roll_Play_3.wav"),
TEXT("Broom/broom_flight_roll_Play_4.wav"),
TEXT("Broom/broom_flight_roll_Play_5.wav"),

TEXT("Broom/broom_flight_roll_right_motion_Play.wav"),

TEXT("Broom/broom_flight_Stop.wav"),
TEXT("Broom/broom_flight_Stop_1.wav"),
TEXT("Broom/broom_flight_Stop_2.wav"),
TEXT("Broom/broom_flight_Stop_3.wav"),
TEXT("Broom/broom_flight_Stop_4.wav"),
TEXT("Broom/broom_flight_Stop_5.wav"),

TEXT("Broom/broom_grab.wav"),

TEXT("Broom/broom_left.wav"),
TEXT("Broom/broom_left_1.wav"),
TEXT("Broom/broom_left_2.wav"),
TEXT("Broom/broom_left_3.wav"),
TEXT("Broom/broom_left_4.wav"),
TEXT("Broom/broom_left_5.wav"),
TEXT("Broom/broom_left_6.wav"),
TEXT("Broom/broom_left_7.wav"),
TEXT("Broom/broom_left_8.wav"),

TEXT("Broom/broom_maneuver.wav"),
TEXT("Broom/broom_maneuver_1.wav"),

TEXT("Broom/broom_maneuver_stop.wav"),
TEXT("Broom/broom_maneuver_stop_1.wav"),

TEXT("Broom/broom_race_bubble_pop_Play.wav"),

TEXT("Broom/broom_right.wav"),
TEXT("Broom/broom_right_1.wav"),
TEXT("Broom/broom_right_2.wav"),
TEXT("Broom/broom_right_3.wav"),
TEXT("Broom/broom_right_4.wav"),
TEXT("Broom/broom_right_5.wav"),
TEXT("Broom/broom_right_6.wav"),
TEXT("Broom/broom_right_7.wav"),
TEXT("Broom/broom_right_8.wav"),

TEXT("Broom/broom_stick_fall_Play.wav"),
TEXT("Broom/broom_stick_fall_Play_1.wav"),

TEXT("Broom/broom_summon.wav"),

TEXT("Broom/broom_up.wav"),
TEXT("Broom/broom_up_1.wav"),
TEXT("Broom/broom_up_2.wav"),
TEXT("Broom/broom_up_3.wav"),
TEXT("Broom/broom_up_4.wav"),
TEXT("Broom/broom_up_5.wav"),
TEXT("Broom/broom_up_6.wav"),
TEXT("Broom/broom_up_7.wav"),
TEXT("Broom/broom_up_8.wav"),

#pragma endregion

#pragma region GOBLIN
	TEXT("Goblin/goblin_0.wav"),
	TEXT("Goblin/goblin_1.wav"),
	TEXT("Goblin/goblin_2.wav"),
	TEXT("Goblin/goblin_3.wav"),
	TEXT("Goblin/goblin_4.wav"),
	TEXT("Goblin/goblin_5.wav"),
	TEXT("Goblin/goblin_6.wav"),
	TEXT("Goblin/goblin_7.wav"),
	TEXT("Goblin/goblin_8.wav"),
	TEXT("Goblin/goblin_9.wav"),
	TEXT("Goblin/goblin_10.wav"),
	TEXT("Goblin/goblin_11.wav"),
	TEXT("Goblin/goblin_12.wav"),
	TEXT("Goblin/goblin_13.wav"),
	TEXT("Goblin/goblin_14.wav"),
	TEXT("Goblin/goblin_15.wav"),
	TEXT("Goblin/goblin_16.wav"),
	TEXT("Goblin/goblin_17.wav"),
	TEXT("Goblin/goblin_18.wav"),
	TEXT("Goblin/goblin_19.wav"),
	TEXT("Goblin/goblin_20.wav"),
	TEXT("Goblin/goblin_21.wav"),
	TEXT("Goblin/goblin_22.wav"),
	TEXT("Goblin/goblin_23.wav"),
	TEXT("Goblin/goblin_24.wav"),
	TEXT("Goblin/goblin_25.wav"),
	TEXT("Goblin/goblin_26.wav"),
	TEXT("Goblin/goblin_27.wav"),
	TEXT("Goblin/goblin_28.wav"),
	TEXT("Goblin/goblin_29.wav"),
	TEXT("Goblin/goblin_30.wav"),
	TEXT("Goblin/goblin_31.wav"),
	TEXT("Goblin/goblin_32.wav"),
	TEXT("Goblin/goblin_33.wav"),
	TEXT("Goblin/goblin_34.wav"),
	TEXT("Goblin/goblin_35.wav"),
	TEXT("Goblin/goblin_36.wav"),
	TEXT("Goblin/goblin_37.wav"),
	TEXT("Goblin/goblin_38.wav"),
	TEXT("Goblin/goblin_39.wav"),
	TEXT("Goblin/goblin_40.wav"),
	TEXT("Goblin/goblin_41.wav"),
	TEXT("Goblin/goblin_42.wav"),
	TEXT("Goblin/goblin_43.wav"),
	TEXT("Goblin/goblin_44.wav"),
	TEXT("Goblin/goblin_45.wav"),
	TEXT("Goblin/goblin_46.wav"),
	TEXT("Goblin/goblin_47.wav"),
	TEXT("Goblin/goblin_48.wav"),
	TEXT("Goblin/goblin_49.wav"),
	TEXT("Goblin/goblin_50.wav"),
	TEXT("Goblin/goblin_51.wav"),
	TEXT("Goblin/goblin_52.wav"),
	TEXT("Goblin/goblin_53.wav"),
	TEXT("Goblin/goblin_54.wav"),
	TEXT("Goblin/goblin_55.wav"),
	TEXT("Goblin/goblin_56.wav"),
	TEXT("Goblin/goblin_57.wav"),
	TEXT("Goblin/goblin_58.wav"),
	TEXT("Goblin/goblin_59.wav"),
	TEXT("Goblin/goblin_60.wav"),
	TEXT("Goblin/goblin_61.wav"),
	TEXT("Goblin/goblin_62.wav"),
	TEXT("Goblin/goblin_63.wav"),
	TEXT("Goblin/goblin_64.wav"),
	TEXT("Goblin/goblin_65.wav"),
	TEXT("Goblin/goblin_66.wav"),
	TEXT("Goblin/goblin_67.wav"),
	TEXT("Goblin/goblin_68.wav"),
	TEXT("Goblin/goblin_69.wav"),
	TEXT("Goblin/goblin_70.wav"),
	TEXT("Goblin/goblin_71.wav"),
	TEXT("Goblin/goblin_72.wav"),
	TEXT("Goblin/goblin_73.wav"),
	TEXT("Goblin/goblin_74.wav"),
	TEXT("Goblin/goblin_75.wav"),
	TEXT("Goblin/goblin_76.wav"),
	TEXT("Goblin/goblin_77.wav"),
	TEXT("Goblin/goblin_78.wav"),
	TEXT("Goblin/goblin_79.wav"),
	TEXT("Goblin/goblin_80.wav"),
	TEXT("Goblin/goblin_81.wav"),
	TEXT("Goblin/goblin_82.wav"),
	TEXT("Goblin/goblin_83.wav"),
	TEXT("Goblin/goblin_84.wav"),
	TEXT("Goblin/goblin_85.wav"),
	TEXT("Goblin/goblin_86.wav"),
	TEXT("Goblin/goblin_87.wav"),
	TEXT("Goblin/goblin_88.wav"),
	TEXT("Goblin/goblin_89.wav"),
	TEXT("Goblin/goblin_90.wav"),
	TEXT("Goblin/goblin_91.wav"),
	TEXT("Goblin/goblin_92.wav"),
	TEXT("Goblin/goblin_93.wav"),
	TEXT("Goblin/goblin_94.wav"),
	TEXT("Goblin/goblin_95.wav"),
	TEXT("Goblin/goblin_96.wav"),
	TEXT("Goblin/goblin_97.wav"),
	TEXT("Goblin/goblin_98.wav"),
	TEXT("Goblin/goblin_99.wav"),
	TEXT("Goblin/goblin_100.wav"),
	TEXT("Goblin/goblin_101.wav"),
	TEXT("Goblin/goblin_102.wav"),
	TEXT("Goblin/goblin_103.wav"),
	TEXT("Goblin/goblin_104.wav"),
	TEXT("Goblin/goblin_105.wav"),
	TEXT("Goblin/goblin_106.wav"),
	TEXT("Goblin/goblin_107.wav"),
	TEXT("Goblin/goblin_108.wav"),
	TEXT("Goblin/goblin_109.wav"),
	TEXT("Goblin/goblin_110.wav"),
	TEXT("Goblin/goblin_111.wav"),
	TEXT("Goblin/goblin_112.wav"),
	TEXT("Goblin/goblin_113.wav"),
	TEXT("Goblin/goblin_114.wav"),
	TEXT("Goblin/goblin_115.wav"),
	TEXT("Goblin/goblin_116.wav"),
	TEXT("Goblin/goblin_117.wav"),
	TEXT("Goblin/goblin_118.wav"),
	TEXT("Goblin/goblin_119.wav"),
	TEXT("Goblin/goblin_120.wav"),
	TEXT("Goblin/goblin_121.wav"),
	TEXT("Goblin/goblin_122.wav"),
	TEXT("Goblin/goblin_123.wav"),
	TEXT("Goblin/goblin_124.wav"),
	TEXT("Goblin/goblin_125.wav"),
	TEXT("Goblin/goblin_126.wav"),
	TEXT("Goblin/goblin_127.wav"),
	TEXT("Goblin/goblin_128.wav"),
	TEXT("Goblin/goblin_129.wav"),
	TEXT("Goblin/goblin_130.wav"),
	TEXT("Goblin/goblin_131.wav"),
	TEXT("Goblin/goblin_132.wav"),
	TEXT("Goblin/goblin_133.wav"),
	TEXT("Goblin/goblin_134.wav"),
	TEXT("Goblin/goblin_135.wav"),
	TEXT("Goblin/goblin_136.wav"),
	TEXT("Goblin/goblin_137.wav"),
	TEXT("Goblin/goblin_138.wav"),
	TEXT("Goblin/goblin_139.wav"),
	TEXT("Goblin/goblin_140.wav"),
	TEXT("Goblin/goblin_141.wav"),
	TEXT("Goblin/goblin_142.wav"),
	TEXT("Goblin/goblin_143.wav"),
	TEXT("Goblin/goblin_144.wav"),
	TEXT("Goblin/goblin_145.wav"),
	TEXT("Goblin/goblin_146.wav"),
	TEXT("Goblin/goblin_147.wav"),
	TEXT("Goblin/goblin_148.wav"),
	TEXT("Goblin/goblin_149.wav"),
	TEXT("Goblin/goblin_150.wav"),
	TEXT("Goblin/Goblin_Mage_Hit.wav"),
	
#pragma endregion

#pragma region GOBLIN_VOICE
	TEXT("Goblin/Voice/goblin_voice_0.wav"),
	TEXT("Goblin/Voice/goblin_voice_1.wav"),
	TEXT("Goblin/Voice/goblin_voice_2.wav"),
	TEXT("Goblin/Voice/goblin_voice_3.wav"),
	TEXT("Goblin/Voice/goblin_voice_4.wav"),
	TEXT("Goblin/Voice/goblin_voice_5.wav"),
	TEXT("Goblin/Voice/goblin_voice_6.wav"),
	TEXT("Goblin/Voice/goblin_voice_7.wav"),
	TEXT("Goblin/Voice/goblin_voice_8.wav"),
	TEXT("Goblin/Voice/goblin_voice_9.wav"),
	TEXT("Goblin/Voice/goblin_voice_10.wav"),
	TEXT("Goblin/Voice/goblin_voice_11.wav"),
	TEXT("Goblin/Voice/goblin_voice_12.wav"),
#pragma endregion
#pragma region DOOR
	TEXT("Interactive/Door/door_open.wav"),
	TEXT("Interactive/Door/door_close.wav"),
#pragma endregion

#pragma region CHEST
	TEXT("Interactive/Chest/chest_found.wav"),
	TEXT("Interactive/Chest/chest_open.wav"),
#pragma endregion

#pragma region RANROK
	TEXT("Ranrok/ranrok_0.wav"),
	TEXT("Ranrok/ranrok_1.wav"),
	TEXT("Ranrok/ranrok_2.wav"),
	TEXT("Ranrok/ranrok_3.wav"),
	TEXT("Ranrok/ranrok_4.wav"),
	TEXT("Ranrok/ranrok_5.wav"),
	TEXT("Ranrok/ranrok_6.wav"),
	TEXT("Ranrok/ranrok_7.wav"),
	TEXT("Ranrok/ranrok_8.wav"),
	TEXT("Ranrok/ranrok_9.wav"),
	TEXT("Ranrok/ranrok_10.wav"),
	TEXT("Ranrok/ranrok_11.wav"),
	TEXT("Ranrok/ranrok_12.wav"),
	TEXT("Ranrok/ranrok_13.wav"),
	TEXT("Ranrok/ranrok_14.wav"),
	TEXT("Ranrok/ranrok_15.wav"),
	TEXT("Ranrok/ranrok_16.wav"),
	TEXT("Ranrok/ranrok_17.wav"),
	TEXT("Ranrok/ranrok_18.wav"),
	TEXT("Ranrok/ranrok_19.wav"),
	TEXT("Ranrok/ranrok_20.wav"),
	TEXT("Ranrok/ranrok_21.wav"),
	TEXT("Ranrok/ranrok_22.wav"),
	TEXT("Ranrok/ranrok_23.wav"),
	TEXT("Ranrok/ranrok_24.wav"),
	TEXT("Ranrok/ranrok_25.wav"),
	TEXT("Ranrok/ranrok_26.wav"),
	TEXT("Ranrok/ranrok_27.wav"),
	TEXT("Ranrok/ranrok_28.wav"),
	TEXT("Ranrok/ranrok_29.wav"),
	TEXT("Ranrok/ranrok_30.wav"),
	TEXT("Ranrok/ranrok_31.wav"),
	TEXT("Ranrok/ranrok_32.wav"),
	TEXT("Ranrok/ranrok_33.wav"),
	TEXT("Ranrok/ranrok_34.wav"),
	TEXT("Ranrok/ranrok_35.wav"),
	TEXT("Ranrok/ranrok_36.wav"),
	TEXT("Ranrok/ranrok_37.wav"),
	TEXT("Ranrok/ranrok_38.wav"),
	TEXT("Ranrok/ranrok_39.wav"),
	TEXT("Ranrok/ranrok_40.wav"),
	TEXT("Ranrok/ranrok_41.wav"),
	TEXT("Ranrok/ranrok_42.wav"),
	TEXT("Ranrok/ranrok_43.wav"),
	TEXT("Ranrok/ranrok_44.wav"),
	TEXT("Ranrok/ranrok_45.wav"),
	TEXT("Ranrok/ranrok_46.wav"),
	TEXT("Ranrok/ranrok_47.wav"),
	TEXT("Ranrok/ranrok_48.wav"),
	TEXT("Ranrok/ranrok_49.wav"),
	TEXT("Ranrok/ranrok_50.wav"),
	TEXT("Ranrok/ranrok_51.wav"),
	TEXT("Ranrok/ranrok_52.wav"),
	TEXT("Ranrok/ranrok_53.wav"),
	TEXT("Ranrok/ranrok_54.wav"),
	TEXT("Ranrok/ranrok_55.wav"),
	TEXT("Ranrok/ranrok_56.wav"),
	TEXT("Ranrok/ranrok_yell.wav"),
	TEXT("Ranrok/ranrock_dragon_burst_wave_rock_loop_Play.wav"),
	TEXT("Ranrok/ranrock_dragon_burst_wave_rock_loop_Stop.wav"),
	TEXT("Ranrok/ranrok_dragon_ambient_control_point_collect.wav"),
	TEXT("Ranrok/ranrok_dragon_burst_wave_shoot_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_burst_wave_start_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_charge_attack.wav"),
	TEXT("Ranrok/ranrok_dragon_charge_attack_1.wav"),
	TEXT("Ranrok/ranrok_dragon_charge_attack_hit.wav"),
	TEXT("Ranrok/ranrok_dragon_ground_wing_hit.wav"),
	TEXT("Ranrok/ranrok_dragon_ground_wing_swipe.wav"),
	TEXT("Ranrok/ranrok_dragon_projectile_grab_impact_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_projectile_impact_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_projectile_passby_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_projectile_shoot_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_projectile_start_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_uppugno_rock_grab_Play.wav"),
	TEXT("Ranrok/ranrok_dragon_uppugno_rock_impact_Play.wav"),

#pragma endregion

#pragma region RANROK_FOOTSTEP
	TEXT("Ranrok/ranrok_Foot_0.wav"),
	TEXT("Ranrok/ranrok_Foot_1.wav"),
	TEXT("Ranrok/ranrok_Foot_2.wav"),
	TEXT("Ranrok/ranrok_Foot_3.wav"),
	TEXT("Ranrok/ranrok_Foot_4.wav"),
	TEXT("Ranrok/ranrok_Foot_5.wav"),
	TEXT("Ranrok/ranrok_Foot_6.wav"),
	TEXT("Ranrok/ranrok_Foot_7.wav"),
	TEXT("Ranrok/ranrok_Foot_8.wav"),
	TEXT("Ranrok/ranrok_Foot_9.wav"),
	TEXT("Ranrok/ranrok_Foot_10.wav"),
	TEXT("Ranrok/ranrok_Foot_11.wav"),
	TEXT("Ranrok/ranrok_Foot_12.wav"),
	TEXT("Ranrok/ranrok_Foot_13.wav"),
	TEXT("Ranrok/ranrok_Foot_14.wav"),
	TEXT("Ranrok/ranrok_Foot_15.wav"),
	TEXT("Ranrok/ranrok_Foot_16.wav"),
	TEXT("Ranrok/ranrok_Foot_17.wav"),
	TEXT("Ranrok/ranrok_Foot_18.wav"),
	TEXT("Ranrok/ranrok_Foot_19.wav"),
	TEXT("Ranrok/ranrok_Foot_20.wav"),
	TEXT("Ranrok/ranrok_Foot_21.wav"),
#pragma endregion

#pragma region TROLL
	TEXT("Troll/troll_0.wav"),
	TEXT("Troll/troll_1.wav"),
	TEXT("Troll/troll_2.wav"),
	TEXT("Troll/troll_3.wav"),
	TEXT("Troll/troll_4.wav"),
	TEXT("Troll/troll_5.wav"),
	TEXT("Troll/troll_6.wav"),
	TEXT("Troll/troll_7.wav"),
	TEXT("Troll/troll_8.wav"),
	TEXT("Troll/troll_9.wav"),
	TEXT("Troll/troll_10.wav"),
	TEXT("Troll/troll_11.wav"),
	TEXT("Troll/troll_12.wav"),
	TEXT("Troll/troll_13.wav"),
	TEXT("Troll/troll_14.wav"),
	TEXT("Troll/troll_15.wav"),
	TEXT("Troll/troll_16.wav"),
	TEXT("Troll/troll_17.wav"),
	TEXT("Troll/troll_18.wav"),
	TEXT("Troll/troll_19.wav"),
	TEXT("Troll/troll_20.wav"),
	TEXT("Troll/troll_21.wav"),
	TEXT("Troll/troll_22.wav"),
	TEXT("Troll/troll_23.wav"),
	TEXT("Troll/troll_24.wav"),
	TEXT("Troll/troll_25.wav"),
	TEXT("Troll/troll_26.wav"),
	TEXT("Troll/troll_27.wav"),
	TEXT("Troll/troll_28.wav"),
	TEXT("Troll/troll_29.wav"),
	TEXT("Troll/troll_30.wav"),
	TEXT("Troll/troll_31.wav"),
	TEXT("Troll/troll_32.wav"),
	TEXT("Troll/troll_33.wav"),
	TEXT("Troll/troll_34.wav"),
	TEXT("Troll/troll_35.wav"),
	TEXT("Troll/troll_36.wav"),
	TEXT("Troll/troll_37.wav"),
	TEXT("Troll/troll_38.wav"),
	TEXT("Troll/troll_39.wav"),
	TEXT("Troll/troll_40.wav"),
	TEXT("Troll/troll_41.wav"),
	TEXT("Troll/troll_42.wav"),
	TEXT("Troll/troll_43.wav"),
	TEXT("Troll/troll_44.wav"),
	TEXT("Troll/troll_45.wav"),
	TEXT("Troll/troll_46.wav"),
	TEXT("Troll/troll_47.wav"),
	TEXT("Troll/troll_48.wav"),
	TEXT("Troll/troll_49.wav"),
	TEXT("Troll/troll_50.wav"),
	TEXT("Troll/troll_51.wav"),
	TEXT("Troll/troll_52.wav"),
	TEXT("Troll/troll_53.wav"),
	TEXT("Troll/troll_54.wav"),
	TEXT("Troll/troll_55.wav"),
	TEXT("Troll/troll_56.wav"),
	TEXT("Troll/troll_57.wav"),
	TEXT("Troll/troll_58.wav"),
	TEXT("Troll/troll_59.wav"),
	TEXT("Troll/troll_60.wav"),
	TEXT("Troll/troll_61.wav"),
	TEXT("Troll/troll_62.wav"),
	TEXT("Troll/troll_63.wav"),
	TEXT("Troll/troll_64.wav"),
	TEXT("Troll/troll_65.wav"),
	TEXT("Troll/troll_66.wav"),
	TEXT("Troll/troll_67.wav"),
	TEXT("Troll/troll_68.wav"),
	TEXT("Troll/troll_69.wav"),
	TEXT("Troll/troll_70.wav"),
	TEXT("Troll/troll_71.wav"),
	TEXT("Troll/troll_72.wav"),
	TEXT("Troll/troll_73.wav"),
	TEXT("Troll/troll_74.wav"),
	TEXT("Troll/troll_75.wav"),
	TEXT("Troll/troll_76.wav"),
	TEXT("Troll/troll_77.wav"),
	TEXT("Troll/troll_78.wav"),
	TEXT("Troll/troll_79.wav"),
	TEXT("Troll/troll_80.wav"),
	TEXT("Troll/troll_81.wav"),
	TEXT("Troll/troll_82.wav"),
	TEXT("Troll/troll_83.wav"),
	TEXT("Troll/troll_84.wav"),
	TEXT("Troll/troll_85.wav"),
	TEXT("Troll/troll_86.wav"),
	TEXT("Troll/troll_87.wav"),
	TEXT("Troll/troll_88.wav"),
	TEXT("Troll/troll_89.wav"),
	TEXT("Troll/troll_90.wav"),
	TEXT("Troll/troll_91.wav"),
	TEXT("Troll/troll_92.wav"),
	TEXT("Troll/troll_93.wav"),
	TEXT("Troll/troll_94.wav"),
	TEXT("Troll/troll_95.wav"),
	TEXT("Troll/troll_96.wav"),
	TEXT("Troll/troll_97.wav"),
	TEXT("Troll/troll_98.wav"),
	TEXT("Troll/troll_99.wav"),
	TEXT("Troll/troll_100.wav"),
	TEXT("Troll/troll_101.wav"),
	TEXT("Troll/fig09_troll_breaks_through_wall_Play.wav"),
	TEXT("Troll/fig09_troll_break_through_wall_Play.wav"),
	TEXT("Troll/fig09_troll_rock_wall_hit_loop_Play.wav"),
	TEXT("Troll/fig09_troll_rock_wall_hit_loop_Stop.wav"),
	TEXT("Troll/fig09_troll_wall_hit_loop_Play.wav"),

	TEXT("Troll/loot_item_troll_mucus_Play.wav"),

	TEXT("Troll/OLI_01_05_TrollAttack_Intro.wav"),
	TEXT("Troll/OLI_01_05_TrollAttack_Intro_1.wav"),
	TEXT("Troll/OLI_01_05_TrollAttack_Outro.wav"),
	TEXT("Troll/OLI_01_05_TrollAttack_Outro_pt1.wav"),
	TEXT("Troll/OLI_01_05_TrollAttack_Outro_pt2.wav"),
	TEXT("Troll/OLI_TrollFight_Building_Broken.wav"),
	TEXT("Troll/OLI_TrollFight_Shot01_Camera_Shake.wav"),

	TEXT("Troll/troll_aggro_roar.wav"),
	TEXT("Troll/troll_armored_club_hit.wav"),
	TEXT("Troll/troll_armored_club_hit_1.wav"),
	TEXT("Troll/troll_armored_overhead_smash_impact.wav"),

	TEXT("Troll/Troll_Attack_1H_R2L.wav"),
	TEXT("Troll/Troll_Attack_2H_Overhead_Slam_Impact.wav"),
	TEXT("Troll/Troll_Attack_2H_Overhead_Slam_Windup.wav"),

	TEXT("Troll/Troll_Attack_RockThrow_HitActor.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitActor_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitBlocked.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitBlocked_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitDeflected.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitDeflected_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitDeflected_2.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTerrain.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTerrain_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTerrain_2.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTroll.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTroll_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTroll_2.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTroll_3.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_HitTroll_4.wav"),

	TEXT("Troll/Troll_Attack_RockThrow_Impact.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_Impact_1.wav"),

	TEXT("Troll/Troll_Attack_RockThrow_LiveLoop.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_LiveLoop_1.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_LiveLoop_2.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_LiveLoop_3.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_LiveLoop_4.wav"),

	TEXT("Troll/Troll_Attack_RockThrow_Projectile_Motion.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_ThrowAtYou.wav"),
	TEXT("Troll/Troll_Attack_RockThrow_Windup.wav"),

	TEXT("Troll/Troll_Attack_Stomp_Impact.wav"),
	TEXT("Troll/Troll_Attack_Stomp_Impact_Motion.wav"),
	TEXT("Troll/Troll_Attack_Stomp_Windup.wav"),

	TEXT("Troll/Troll_Attack_Swing.wav"),
	TEXT("Troll/Troll_Attack_Swing_1.wav"),
	TEXT("Troll/Troll_Attack_Swing_2.wav"),
	TEXT("Troll/Troll_Attack_Swing_3.wav"),
	TEXT("Troll/Troll_Attack_Swing_4.wav"),
	TEXT("Troll/Troll_Attack_Swing_5.wav"),
	TEXT("Troll/Troll_Attack_Swing_6.wav"),
	TEXT("Troll/Troll_Attack_Swing_7.wav"),

	TEXT("Troll/troll_charge_attack_hit.wav"),
	TEXT("Troll/troll_charge_attack_start.wav"),

	TEXT("Troll/troll_club_hit.wav"),
	TEXT("Troll/troll_club_swing.wav"),

	TEXT("Troll/Troll_Fight_box_crash_pile_1.wav"),
	TEXT("Troll/Troll_Fight_box_crash_pile_2.wav"),
	TEXT("Troll/Troll_Fight_object_repair_A2.wav"),
	TEXT("Troll/Troll_Fight_object_repair_B.wav"),
	TEXT("Troll/Troll_Fight_object_repair_C.wav"),
	TEXT("Troll/Troll_Fight_reparo_shack.wav"),
	TEXT("Troll/Troll_Fight_reparo_shack2.wav"),
	TEXT("Troll/Troll_Fight_reparo_statue.wav"),

	TEXT("Troll/Troll_Idle_Grass_Wipe_01.wav"),
	TEXT("Troll/Troll_Idle_Grass_Wipe_02.wav"),
	TEXT("Troll/Troll_Idle_Grass_Wipe_03.wav"),

	TEXT("Troll/Troll_Idle_Scratch_Armpit.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Armpit_1.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Armpit_2.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Armpit_Flick_Wrist_01.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Armpit_Flick_Wrist_02.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Armpit_Flick_Wrist_03.wav"),

	TEXT("Troll/Troll_Idle_Scratch_Butt.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_1.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_2.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_3.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_4.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_5.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_6.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_7.wav"),
	TEXT("Troll/Troll_Idle_Scratch_Butt_Flick_Wrist.wav"),

	TEXT("Troll/troll_overhead_smash_impact.wav"),

	TEXT("Troll/Troll_Ragdoll_Body_Foley.wav"),
	TEXT("Troll/Troll_Ragdoll_Body_Foley_1.wav"),
	TEXT("Troll/Troll_Ragdoll_Body_Foley_2.wav"),
	TEXT("Troll/Troll_Ragdoll_Body_Foley_3.wav"),

	TEXT("Troll/troll_rock_oppugno_impact_Play.wav"),
	TEXT("Troll/troll_rock_oppugno_impact_Play_1.wav"),

	TEXT("Troll/troll_rock_throw.wav"),
	TEXT("Troll/troll_rock_throw_1.wav"),
	TEXT("Troll/troll_rock_throw_2.wav"),
	TEXT("Troll/troll_rock_throw_3.wav"),
	TEXT("Troll/troll_rock_throw_rock_land.wav"),
	TEXT("Troll/troll_rock_throw_start.wav"),
	TEXT("Troll/troll_rock_throw_troll_hit.wav"),

	TEXT("Troll/Troll_Smash_Motion.wav"),

	TEXT("Troll/troll_stone_impact_large.wav"),
	TEXT("Troll/troll_stone_impact_large_1.wav"),
	TEXT("Troll/troll_stone_impact_large_2.wav"),
	TEXT("Troll/troll_stone_impact_large_3.wav"),
	TEXT("Troll/troll_stone_impact_large_4.wav"),

	TEXT("Troll/Troll_Stop_Attack_SFX.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_1.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_10.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_2.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_3.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_4.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_5.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_6.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_7.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_8.wav"),
	TEXT("Troll/Troll_Stop_Attack_SFX_9.wav"),

	TEXT("Troll/Troll_Swipe_Melee_Hand_Impact.wav"),

	TEXT("Troll/Troll_wall_impact.wav"),

	TEXT("Troll/vo_troll_charge_attack_1.wav"),
	TEXT("Troll/vo_troll_charge_attack_end.wav"),
	TEXT("Troll/vo_troll_charge_attack_loop.wav"),
	TEXT("Troll/vo_troll_charge_attack_loop_Stop.wav"),
	TEXT("Troll/vo_troll_charge_rage_attack.wav"),
	TEXT("Troll/vo_troll_charge_rage_attack_end_Play.wav"),
	TEXT("Troll/vo_troll_charge_rage_attack_Play.wav"),

		TEXT("Troll/troll_foot_impact.wav"),
		TEXT("Troll/troll_foot_impact_1.wav"),
		TEXT("Troll/troll_foot_impact_2.wav"),
		TEXT("Troll/troll_foot_impact_3.wav"),
		TEXT("Troll/troll_foot_impact_4.wav"),
		TEXT("Troll/troll_foot_impact_5.wav"),
		TEXT("Troll/troll_foot_impact_6.wav"),
		TEXT("Troll/troll_foot_impact_7.wav"),
		TEXT("Troll/troll_foot_impact_8.wav"),
		TEXT("Troll/troll_foot_impact_9.wav"),
		TEXT("Troll/troll_foot_impact_10.wav"),
		TEXT("Troll/troll_foot_impact_11.wav"),




#pragma endregion



#pragma region FX
	TEXT("FX/fx_sound_0.wav"),
	TEXT("FX/fx_sound_1.wav"),
	TEXT("FX/fx_sound_2.wav"),
	TEXT("FX/fx_sound_3.wav"),
	TEXT("FX/fx_sound_4.wav"),
	TEXT("FX/fx_sound_6.wav"),
	TEXT("FX/fx_sound_7.wav"),
	TEXT("FX/fx_sound_8.wav"),
	TEXT("FX/fx_sound_9.wav"),
	TEXT("FX/fx_sound_10.wav"),
	TEXT("FX/fx_sound_11.wav"),
	TEXT("FX/fx_sound_12.wav"),
	TEXT("FX/fx_sound_13.wav"),
	TEXT("FX/fx_sound_14.wav"),
	TEXT("FX/fx_sound_15.wav"),
	TEXT("FX/fx_sound_16.wav"),
	TEXT("FX/fireworks-402788.wav"),
	TEXT("FX/CountDown.wav"),
#pragma endregion
#pragma region PROP_BROKEN
	TEXT("Prop/Wood0.wav"),
	TEXT("Prop/Wood1.wav"),
	TEXT("Prop/Wood2.wav"),
	TEXT("Prop/Barrel0.wav"),
	TEXT("Prop/Barrel1.wav"),
	TEXT("Prop/Barrel2.wav"),
	TEXT("Prop/paper0.wav"),
	TEXT("Prop/paper1.wav"),
	TEXT("Prop/paper2.wav"),
	TEXT("Prop/Box0.wav"),
	TEXT("Prop/Box1.wav"),
#pragma endregion

#pragma region UI
	TEXT("UI/Logo_Intro.wav"),
#pragma endregion


#pragma region DOBI
	TEXT("Dobi/dobi_voice.wav"),
#pragma endregion
#pragma region PLAYERHIT
	TEXT("Player/Hit/PlayerHit0.wav"),
	TEXT("Player/Hit/PlayerHit1.wav"),
	TEXT("Player/Hit/PlayerHit2.wav"),
	TEXT("Player/Hit/PlayerHit3.wav"),
#pragma endregion


#pragma region TUCKED_SWAM
		TEXT("Player/spells_wand_doppler_akb/wand_doppler0.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler1.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler2.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler3.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler4.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler5.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler6.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler7.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler8.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler9.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler10.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler11.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler12.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler13.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler14.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler15.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler16.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler17.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler18.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler19.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler20.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler21.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler22.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler23.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler24.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler25.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler26.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler27.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler28.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler29.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler30.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler31.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler32.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler33.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler34.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler35.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler36.wav"),
		TEXT("Player/spells_wand_doppler_akb/wand_doppler37.wav"),
#pragma endregion
};

static_assert(SD_KIND_COUNT == _countof(SD_PATH::SD_KIND_PATHS),
	"SD_KIND and SD_PATH::SD_KIND_PATHS num is not match" "match same num");
