#include "pch.h"
#include "Engine_Define.h"
#include "SoundSrc.h"


using namespace Engine::SOUND;

const _tchar* const SD_PATH::SD_KIND_PATHS[SD_KIND_COUNT] = {
#pragma region BGM
	TEXT("BGM/battle_BGM_0.wav"), 
	TEXT("BGM/battle_BGM_1.wav"), 
	TEXT("BGM/grassland_day.wav"), 
	TEXT("BGM/grassland_night.wav"), 
	TEXT("BGM/hogwart_BGM_0.wav"), 
	TEXT("BGM/hogwart_BGM_1.wav"), 
	TEXT("BGM/hogwart_BGM_int.wav"), 
	TEXT("BGM/Ranrok_BGM.wav"), 
#pragma endregion

#pragma region FOOTSTEP
	TEXT("Player/footsteps/step_int.wav"),
	TEXT("Player/footsteps/step_road.wav"),
	TEXT("Player/footsteps/step_rock.wav"),
	TEXT("Player/footsteps/step_terrain.wav"),
#pragma endregion


#pragma region SPELL
	TEXT("Player/spells_jap_akb/jap_0.wav"), 
	TEXT("Player/spells_jap_akb/jap_1.wav"),
	TEXT("Player/spells_jap_akb/jap_13.wav"),
	TEXT("Player/spells_perk_shadowblink_akb/blink_2.wav"),
#pragma endregion

#pragma region AVADA_KEDAVRA
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_0.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_1.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_2.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_3.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_4.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_5.wav"), // 5
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_6.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_7.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_8.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_9.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_10.wav"), // 10
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_11.wav"),
	TEXT("Player/spells_avada_kedavra_akb/avada_kedavra_12.wav"),
#pragma endregion

#pragma region ANCIENT_LIGHTNING
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_0.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_1.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_2.wav"),
	TEXT("Player/spells_finisher_am_lightningstrike_akb/lightnig_3.wav"),
#pragma endregion

#pragma region ACCIO

	TEXT("Player/spells_accio_akb/accio_0.wav"),
	TEXT("Player/spells_accio_akb/accio_1.wav"),
	TEXT("Player/spells_accio_akb/accio_2.wav"),
	TEXT("Player/spells_accio_akb/accio_3.wav"),
	TEXT("Player/spells_accio_akb/accio_4.wav"),
	TEXT("Player/spells_accio_akb/accio_5.wav"),
	TEXT("Player/spells_accio_akb/accio_6.wav"),
	TEXT("Player/spells_accio_akb/accio_7.wav"),
	TEXT("Player/spells_accio_akb/accio_8.wav"),
	TEXT("Player/spells_accio_akb/accio_9.wav"),
	TEXT("Player/spells_accio_akb/accio_10.wav"),
	TEXT("Player/spells_accio_akb/accio_11.wav"),
	TEXT("Player/spells_accio_akb/accio_12.wav"),
	TEXT("Player/spells_accio_akb/accio_13.wav"),
	TEXT("Player/spells_accio_akb/accio_14.wav"),
	TEXT("Player/spells_accio_akb/accio_15.wav"),
	TEXT("Player/spells_accio_akb/accio_16.wav"),
	TEXT("Player/spells_accio_akb/accio_17.wav"),
	TEXT("Player/spells_accio_akb/accio_18.wav"),
	TEXT("Player/spells_accio_akb/accio_19.wav"),
	TEXT("Player/spells_accio_akb/accio_20.wav"),
	TEXT("Player/spells_accio_akb/accio_21.wav"),
	TEXT("Player/spells_accio_akb/accio_22.wav"),
	TEXT("Player/spells_accio_akb/accio_23.wav"),

#pragma endregion

#pragma region REPARO
	TEXT("Player/spells_reparo_akb/reparo_0.wav"),
	TEXT("Player/spells_reparo_akb/reparo_11.wav"),
	TEXT("Player/spells_reparo_akb/reparo_21.wav"),
#pragma endregion

#pragma region DECENDO

	TEXT("Player/spells_descendo_akb/descendo_0.wav"),
	TEXT("Player/spells_descendo_akb/descendo_1.wav"),
	TEXT("Player/spells_descendo_akb/descendo_2.wav"),
	TEXT("Player/spells_descendo_akb/descendo_3.wav"),
	TEXT("Player/spells_descendo_akb/descendo_4.wav"),
	TEXT("Player/spells_descendo_akb/descendo_5.wav"),
	TEXT("Player/spells_descendo_akb/descendo_6.wav"),
	TEXT("Player/spells_descendo_akb/descendo_7.wav"),
	TEXT("Player/spells_descendo_akb/descendo_8.wav"),
	TEXT("Player/spells_descendo_akb/descendo_9.wav"),
	TEXT("Player/spells_descendo_akb/descendo_10.wav"),
	TEXT("Player/spells_descendo_akb/descendo_11.wav"),
	TEXT("Player/spells_descendo_akb/descendo_12.wav"),
	TEXT("Player/spells_descendo_akb/descendo_13.wav"),
	TEXT("Player/spells_descendo_akb/descendo_14.wav"),
	TEXT("Player/spells_descendo_akb/descendo_15.wav"),
	TEXT("Player/spells_descendo_akb/descendo_16.wav"),
	TEXT("Player/spells_descendo_akb/descendo_17.wav"),
	TEXT("Player/spells_descendo_akb/descendo_18.wav"),
	TEXT("Player/spells_descendo_akb/descendo_19.wav"),
	TEXT("Player/spells_descendo_akb/descendo_20.wav"),
	TEXT("Player/spells_descendo_akb/descendo_21.wav"),
	TEXT("Player/spells_descendo_akb/descendo_22.wav"),
	TEXT("Player/spells_descendo_akb/descendo_23.wav"),
	TEXT("Player/spells_descendo_akb/descendo_24.wav"),
	TEXT("Player/spells_descendo_akb/descendo_25.wav"),

#pragma endregion


#pragma region BOMBARD

	TEXT("Player/spells_bombard_akb/bombard_0.wav"),
	TEXT("Player/spells_bombard_akb/bombard_1.wav"),
	TEXT("Player/spells_bombard_akb/bombard_2.wav"),
	TEXT("Player/spells_bombard_akb/bombard_3.wav"),
	TEXT("Player/spells_bombard_akb/bombard_4.wav"),
	TEXT("Player/spells_bombard_akb/bombard_5.wav"),
	TEXT("Player/spells_bombard_akb/bombard_6.wav"),
	TEXT("Player/spells_bombard_akb/bombard_7.wav"),
	TEXT("Player/spells_bombard_akb/bombard_8.wav"),
	TEXT("Player/spells_bombard_akb/bombard_9.wav"),
	TEXT("Player/spells_bombard_akb/bombard_10.wav"),
	TEXT("Player/spells_bombard_akb/bombard_11.wav"),
	TEXT("Player/spells_bombard_akb/bombard_12.wav"),
	TEXT("Player/spells_bombard_akb/bombard_13.wav"),
	TEXT("Player/spells_bombard_akb/bombard_14.wav"),
	TEXT("Player/spells_bombard_akb/bombard_15.wav"),
	TEXT("Player/spells_bombard_akb/bombard_16.wav"),
	TEXT("Player/spells_bombard_akb/bombard_17.wav"),
	TEXT("Player/spells_bombard_akb/bombard_18.wav"),
	TEXT("Player/spells_bombard_akb/bombard_19.wav"),
	TEXT("Player/spells_bombard_akb/bombard_20.wav"),
	TEXT("Player/spells_bombard_akb/bombard_21.wav"),
	TEXT("Player/spells_bombard_akb/bombard_22.wav"),
	TEXT("Player/spells_bombard_akb/bombard_23.wav"),
	TEXT("Player/spells_bombard_akb/bombard_24.wav"),
	TEXT("Player/spells_bombard_akb/bombard_25.wav"),
	TEXT("Player/spells_bombard_akb/bombard_26.wav"),
	TEXT("Player/spells_bombard_akb/bombard_27.wav"),
	TEXT("Player/spells_bombard_akb/bombard_28.wav"),
	TEXT("Player/spells_bombard_akb/bombard_29.wav"),
	TEXT("Player/spells_bombard_akb/bombard_30.wav"),
	TEXT("Player/spells_bombard_akb/bombard_31.wav"),
	TEXT("Player/spells_bombard_akb/bombard_32.wav"),
	TEXT("Player/spells_bombard_akb/bombard_33.wav"),
	TEXT("Player/spells_bombard_akb/bombard_34.wav"),
	TEXT("Player/spells_bombard_akb/bombard_35.wav"),
	TEXT("Player/spells_bombard_akb/bombard_36.wav"),
	TEXT("Player/spells_bombard_akb/bombard_37.wav"),
	TEXT("Player/spells_bombard_akb/bombard_38.wav"),
	TEXT("Player/spells_bombard_akb/bombard_39.wav"),
	TEXT("Player/spells_bombard_akb/bombard_40.wav"),
	TEXT("Player/spells_bombard_akb/bombard_41.wav"),
	TEXT("Player/spells_bombard_akb/bombard_42.wav"),
	TEXT("Player/spells_bombard_akb/bombard_43.wav"),
	TEXT("Player/spells_bombard_akb/bombard_44.wav"),
	TEXT("Player/spells_bombard_akb/bombard_45.wav"),
	TEXT("Player/spells_bombard_akb/bombard_46.wav"),
#pragma endregion

#pragma region LEVIOSA
		TEXT("Player/spells_leviosa_akb/leviosa_0.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_1.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_2.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_3.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_4.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_5.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_6.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_7.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_8.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_9.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_10.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_11.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_12.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_13.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_14.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_15.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_16.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_17.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_18.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_19.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_20.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_21.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_22.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_23.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_24.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_25.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_26.wav"),
		TEXT("Player/spells_leviosa_akb/leviosa_27.wav"),

#pragma endregion

#pragma region PROTEGO

		TEXT("Player/spells_protego_akb/protego_0.wav"),
		TEXT("Player/spells_protego_akb/protego_1.wav"),
		TEXT("Player/spells_protego_akb/protego_2.wav"),
		TEXT("Player/spells_protego_akb/protego_3.wav"),
		TEXT("Player/spells_protego_akb/protego_4.wav"),
		TEXT("Player/spells_protego_akb/protego_5.wav"),
		TEXT("Player/spells_protego_akb/protego_6.wav"),
		TEXT("Player/spells_protego_akb/protego_7.wav"),
		TEXT("Player/spells_protego_akb/protego_8.wav"),
		TEXT("Player/spells_protego_akb/protego_9.wav"),
		TEXT("Player/spells_protego_akb/protego_10.wav"),
		TEXT("Player/spells_protego_akb/protego_11.wav"),
		TEXT("Player/spells_protego_akb/protego_12.wav"),
		TEXT("Player/spells_protego_akb/protego_13.wav"),
		TEXT("Player/spells_protego_akb/protego_14.wav"),
		TEXT("Player/spells_protego_akb/protego_15.wav"),
		TEXT("Player/spells_protego_akb/protego_16.wav"),
		TEXT("Player/spells_protego_akb/protego_17.wav"),
		TEXT("Player/spells_protego_akb/protego_18.wav"),
		TEXT("Player/spells_protego_akb/protego_19.wav"),
		TEXT("Player/spells_protego_akb/protego_20.wav"),
		TEXT("Player/spells_protego_akb/protego_21.wav"),
		TEXT("Player/spells_protego_akb/protego_22.wav"),
		TEXT("Player/spells_protego_akb/protego_23.wav"),
		TEXT("Player/spells_protego_akb/protego_24.wav"),
		TEXT("Player/spells_protego_akb/protego_25.wav"),
		TEXT("Player/spells_protego_akb/protego_26.wav"),
		TEXT("Player/spells_protego_akb/protego_27.wav"),
		TEXT("Player/spells_protego_akb/protego_28.wav"),
		TEXT("Player/spells_protego_akb/protego_29.wav"),
		TEXT("Player/spells_protego_akb/protego_30.wav"),

#pragma endregion




#pragma region LUMOS
		TEXT("Player/spells_lumos_akb/lumos_0.wav"),
		TEXT("Player/spells_lumos_akb/lumos_1.wav"),
#pragma endregion

#pragma region VOICE
	TEXT("Player/Voice/avadakedavra_voice.wav"),
	TEXT("Player/Voice/bombarda_voice.wav"),
	TEXT("Player/Voice/decendo_voice.wav"),
	TEXT("Player/Voice/levioso_voice.wav"),
	TEXT("Player/Voice/lumos_voice.wav"),
	TEXT("Player/Voice/protego_voice.wav"),
	TEXT("Player/Voice/reparo_voice.wav"),
	TEXT("Player/Voice/revelio.voice.wav"),
	TEXT("Player/Voice/stupefy_voice.wav"),
#pragma endregion

#pragma region BROOM
	TEXT("Player/Broom/broom_boost.wav"),
	TEXT("Player/Broom/broom_down.wav"),
	TEXT("Player/Broom/broom_get_item.wav"),
	TEXT("Player/Broom/broom_normal.wav"),
	TEXT("Player/Broom/broom_ride.wav"),
#pragma endregion

#pragma region DOOR
	TEXT("Interactive/Door/door_open.wav"),
	TEXT("Interactive/Door/door_close.wav"),
#pragma endregion

#pragma region CHEST
	TEXT("Interactive/Chest/chest_found.wav"),
	TEXT("Interactive/Chest/chest_open.wav"),
#pragma endregion

#pragma region RANROK
	TEXT("Ranrok/ranrok_0.wav"),
	TEXT("Ranrok/ranrok_1.wav"),
	TEXT("Ranrok/ranrok_2.wav"),
	TEXT("Ranrok/ranrok_3.wav"),
	TEXT("Ranrok/ranrok_4.wav"),
	TEXT("Ranrok/ranrok_5.wav"),
	TEXT("Ranrok/ranrok_6.wav"),
	TEXT("Ranrok/ranrok_7.wav"),
	TEXT("Ranrok/ranrok_8.wav"),
	TEXT("Ranrok/ranrok_9.wav"),
	TEXT("Ranrok/ranrok_10.wav"),
	TEXT("Ranrok/ranrok_11.wav"),
	TEXT("Ranrok/ranrok_12.wav"),
	TEXT("Ranrok/ranrok_13.wav"),
	TEXT("Ranrok/ranrok_14.wav"),
	TEXT("Ranrok/ranrok_15.wav"),
	TEXT("Ranrok/ranrok_16.wav"),
	TEXT("Ranrok/ranrok_17.wav"),
	TEXT("Ranrok/ranrok_18.wav"),
	TEXT("Ranrok/ranrok_19.wav"),
	TEXT("Ranrok/ranrok_20.wav"),
	TEXT("Ranrok/ranrok_21.wav"),
	TEXT("Ranrok/ranrok_22.wav"),
	TEXT("Ranrok/ranrok_23.wav"),
	TEXT("Ranrok/ranrok_24.wav"),
	TEXT("Ranrok/ranrok_25.wav"),
	TEXT("Ranrok/ranrok_26.wav"),
	TEXT("Ranrok/ranrok_27.wav"),
	TEXT("Ranrok/ranrok_28.wav"),
	TEXT("Ranrok/ranrok_29.wav"),
	TEXT("Ranrok/ranrok_30.wav"),
	TEXT("Ranrok/ranrok_31.wav"),
	TEXT("Ranrok/ranrok_32.wav"),
	TEXT("Ranrok/ranrok_33.wav"),
	TEXT("Ranrok/ranrok_34.wav"),
	TEXT("Ranrok/ranrok_35.wav"),
	TEXT("Ranrok/ranrok_36.wav"),
	TEXT("Ranrok/ranrok_37.wav"),
	TEXT("Ranrok/ranrok_38.wav"),
	TEXT("Ranrok/ranrok_39.wav"),
	TEXT("Ranrok/ranrok_40.wav"),
	TEXT("Ranrok/ranrok_41.wav"),
	TEXT("Ranrok/ranrok_42.wav"),
	TEXT("Ranrok/ranrok_43.wav"),
	TEXT("Ranrok/ranrok_44.wav"),
	TEXT("Ranrok/ranrok_45.wav"),
	TEXT("Ranrok/ranrok_46.wav"),
	TEXT("Ranrok/ranrok_47.wav"),
	TEXT("Ranrok/ranrok_48.wav"),
	TEXT("Ranrok/ranrok_49.wav"),
	TEXT("Ranrok/ranrok_50.wav"),
	TEXT("Ranrok/ranrok_51.wav"),
	TEXT("Ranrok/ranrok_52.wav"),
	TEXT("Ranrok/ranrok_53.wav"),
	TEXT("Ranrok/ranrok_54.wav"),
	TEXT("Ranrok/ranrok_55.wav"),
	TEXT("Ranrok/ranrok_56.wav"),
	TEXT("Ranrok/ranrok_yell.wav"),
#pragma endregion

#pragma region RANROK_FOOTSTEP
	TEXT("Ranrok/ranrok_Foot_0.wav"),
	TEXT("Ranrok/ranrok_Foot_1.wav"),
	TEXT("Ranrok/ranrok_Foot_2.wav"),
	TEXT("Ranrok/ranrok_Foot_3.wav"),
	TEXT("Ranrok/ranrok_Foot_4.wav"),
	TEXT("Ranrok/ranrok_Foot_5.wav"),
	TEXT("Ranrok/ranrok_Foot_6.wav"),
	TEXT("Ranrok/ranrok_Foot_7.wav"),
	TEXT("Ranrok/ranrok_Foot_8.wav"),
	TEXT("Ranrok/ranrok_Foot_9.wav"),
	TEXT("Ranrok/ranrok_Foot_10.wav"),
	TEXT("Ranrok/ranrok_Foot_11.wav"),
	TEXT("Ranrok/ranrok_Foot_12.wav"),
	TEXT("Ranrok/ranrok_Foot_13.wav"),
	TEXT("Ranrok/ranrok_Foot_14.wav"),
	TEXT("Ranrok/ranrok_Foot_15.wav"),
	TEXT("Ranrok/ranrok_Foot_16.wav"),
	TEXT("Ranrok/ranrok_Foot_17.wav"),
	TEXT("Ranrok/ranrok_Foot_18.wav"),
	TEXT("Ranrok/ranrok_Foot_19.wav"),
	TEXT("Ranrok/ranrok_Foot_20.wav"),
	TEXT("Ranrok/ranrok_Foot_21.wav"),
#pragma endregion

#pragma region TROLL
	TEXT("Troll/troll_0.wav"),
	TEXT("Troll/troll_1.wav"),
	TEXT("Troll/troll_2.wav"),
	TEXT("Troll/troll_3.wav"),
	TEXT("Troll/troll_4.wav"),
	TEXT("Troll/troll_5.wav"),
	TEXT("Troll/troll_6.wav"),
	TEXT("Troll/troll_7.wav"),
	TEXT("Troll/troll_8.wav"),
	TEXT("Troll/troll_9.wav"),
	TEXT("Troll/troll_10.wav"),
	TEXT("Troll/troll_11.wav"),
	TEXT("Troll/troll_12.wav"),
	TEXT("Troll/troll_13.wav"),
	TEXT("Troll/troll_14.wav"),
	TEXT("Troll/troll_15.wav"),
	TEXT("Troll/troll_16.wav"),
	TEXT("Troll/troll_17.wav"),
	TEXT("Troll/troll_18.wav"),
	TEXT("Troll/troll_19.wav"),
	TEXT("Troll/troll_20.wav"),
	TEXT("Troll/troll_21.wav"),
	TEXT("Troll/troll_22.wav"),
	TEXT("Troll/troll_23.wav"),
	TEXT("Troll/troll_24.wav"),
	TEXT("Troll/troll_25.wav"),
	TEXT("Troll/troll_26.wav"),
	TEXT("Troll/troll_27.wav"),
	TEXT("Troll/troll_28.wav"),
	TEXT("Troll/troll_29.wav"),
	TEXT("Troll/troll_30.wav"),
	TEXT("Troll/troll_31.wav"),
	TEXT("Troll/troll_32.wav"),
	TEXT("Troll/troll_33.wav"),
	TEXT("Troll/troll_34.wav"),
	TEXT("Troll/troll_35.wav"),
	TEXT("Troll/troll_36.wav"),
	TEXT("Troll/troll_37.wav"),
	TEXT("Troll/troll_38.wav"),
	TEXT("Troll/troll_39.wav"),
	TEXT("Troll/troll_40.wav"),
	TEXT("Troll/troll_41.wav"),
	TEXT("Troll/troll_42.wav"),
	TEXT("Troll/troll_43.wav"),
	TEXT("Troll/troll_44.wav"),
	TEXT("Troll/troll_45.wav"),
	TEXT("Troll/troll_46.wav"),
	TEXT("Troll/troll_47.wav"),
	TEXT("Troll/troll_48.wav"),
	TEXT("Troll/troll_49.wav"),
	TEXT("Troll/troll_50.wav"),
	TEXT("Troll/troll_51.wav"),
	TEXT("Troll/troll_52.wav"),
	TEXT("Troll/troll_53.wav"),
	TEXT("Troll/troll_54.wav"),
	TEXT("Troll/troll_55.wav"),
	TEXT("Troll/troll_56.wav"),
	TEXT("Troll/troll_57.wav"),
	TEXT("Troll/troll_58.wav"),
	TEXT("Troll/troll_59.wav"),
	TEXT("Troll/troll_60.wav"),
	TEXT("Troll/troll_61.wav"),
	TEXT("Troll/troll_62.wav"),
	TEXT("Troll/troll_63.wav"),
	TEXT("Troll/troll_64.wav"),
	TEXT("Troll/troll_65.wav"),
	TEXT("Troll/troll_66.wav"),
	TEXT("Troll/troll_67.wav"),
	TEXT("Troll/troll_68.wav"),
	TEXT("Troll/troll_69.wav"),
	TEXT("Troll/troll_70.wav"),
	TEXT("Troll/troll_71.wav"),
	TEXT("Troll/troll_72.wav"),
	TEXT("Troll/troll_73.wav"),
	TEXT("Troll/troll_74.wav"),
	TEXT("Troll/troll_75.wav"),
	TEXT("Troll/troll_76.wav"),
	TEXT("Troll/troll_77.wav"),
	TEXT("Troll/troll_78.wav"),
	TEXT("Troll/troll_79.wav"),
	TEXT("Troll/troll_80.wav"),
	TEXT("Troll/troll_81.wav"),
	TEXT("Troll/troll_82.wav"),
	TEXT("Troll/troll_83.wav"),
	TEXT("Troll/troll_84.wav"),
	TEXT("Troll/troll_85.wav"),
	TEXT("Troll/troll_86.wav"),
	TEXT("Troll/troll_87.wav"),
	TEXT("Troll/troll_88.wav"),
	TEXT("Troll/troll_89.wav"),
	TEXT("Troll/troll_90.wav"),
	TEXT("Troll/troll_91.wav"),
	TEXT("Troll/troll_92.wav"),
	TEXT("Troll/troll_93.wav"),
	TEXT("Troll/troll_94.wav"),
	TEXT("Troll/troll_95.wav"),
	TEXT("Troll/troll_96.wav"),
	TEXT("Troll/troll_97.wav"),
	TEXT("Troll/troll_98.wav"),
	TEXT("Troll/troll_99.wav"),
	TEXT("Troll/troll_100.wav"),
	TEXT("Troll/troll_101.wav"),

#pragma endregion

#pragma region FX
	TEXT("FX/fx_sound_0.wav"),
	TEXT("FX/fx_sound_1.wav"),
	TEXT("FX/fx_sound_2.wav"),
	TEXT("FX/fx_sound_3.wav"),
	TEXT("FX/fx_sound_4.wav"),
	TEXT("FX/fx_sound_6.wav"),
	TEXT("FX/fx_sound_7.wav"),
	TEXT("FX/fx_sound_8.wav"),
	TEXT("FX/fx_sound_9.wav"),
	TEXT("FX/fx_sound_10.wav"),
	TEXT("FX/fx_sound_11.wav"),
	TEXT("FX/fx_sound_12.wav"),
	TEXT("FX/fx_sound_13.wav"),
	TEXT("FX/fx_sound_14.wav"),
	TEXT("FX/fx_sound_15.wav"),
	TEXT("FX/fx_sound_16.wav"),

#pragma endregion


};

static_assert(SD_KIND_COUNT == _countof(SD_PATH::SD_KIND_PATHS), 
	"SD_KIND and SD_PATH::SD_KIND_PATHS num is not match" "match same num");
