#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, INTRO, GAMEPLAY, FIELD, RESTART, END };
	enum class MAPOBJECT_TYPE { CONTAINER, ELEMENT_STATIC, ELEMENT_INTERACT };
	enum class MAPOBJECT_RENDER_TYPE { NORMAL, DECAL, GLASS };

	enum class SHADER_PASS_ANIM { DEFAULT, SHADOW, CAPTURE, BLUR, HAIR, EYELASH, OUTLINE_WRITE, OUTLINE_READ,SPECTOR, END };
	enum class SHADER_PASS_MESH { DEFAULT, SHADOW, SKYBOX, ALPHABLEND, EFFECT_ALPHABLEND, EFFECT_BLEND, EFFECT_ALPHABLEND_CULL, EFFECT_BLEND_CULL, CAPTURE, BLUR, EFFECT_ALPHABLEND_UVMOVE, MAPTOOL, GLASS, OUTLINE_WRITE, OUTLINE_READ, BLOOM, WATER, LAND, NONMRO,SPECTOR_WEAPON, GLASS_CUBE, LEVIOSO, DECAL, END };
	enum class SHADER_PASS_NORTEX { DEFAULT, TERRAIN, ENV_TERRAIN_ANISO, SHADOW, END };
	enum class SHADER_PASS_PARTICLE { EXPLOSION, END };
	enum class SHADER_PASS_POSTEX { DEFAULT, SCISSOR, UI, UVMOVE, TRAIL, TRAIL_BLEND, TRAILWB_FOR_BLEND, TRAIL_BLUR, TRAIL_BLOOM, END };
	enum class SHADER_PASS_INSTANCE_MODEL { DEFAULT, NON_NOMALMAP, BLUR, WEIGHTBLEND, NON_WORLD, NON_WORLD_BLUR, BLEND, BLEND_NOWORLD, BLOOM, BLOOM_NOWORLD, BLUR_NO_EMMISVE, BLUR_NO_WORLD_NO_EMISSIVE, WEIGHTBLEND_FOR_BLEND, DEPTH_STOP, WB_CULLING, SCREEN_FX, DISTORTION, NONPOS, NONPOS_BLUR , BLUR_MESH, BLUR_CULLING, BLUR_CULLING_NO_EMISSIVE, BLOOM_CULLING, END};
	enum class SHADER_PASS_UIEDITOR {
		DEFAULT, COLOR, LOGO, LOGO_TEXT, LOGO_GLOW, ALPHABLEND, CLAMP, CURSOR,
		LODING, HOLD_ROTATION, MISSION, QUESTTYPE, UVMULT, NINECLICE,
		ROTATION, SLOT, TYPE, HPBAR, MAGIC_METER, MAGIC_ICON, REMOVEUV,
		REVELIO, POTION, MAGIC_ITEM, SPELL_PREVIEW, SPELL_HEADER,
		SPELL_HEADER_LINE, SPELL_DRAG, CAMERA_LOCKON, LODING_SCREEN,
		ENEMY_HPBAR, BOSS_HPBAR, QUEST_BORDER, QUEST_INFO, QUEST_STATUS, BROOMSTICK,
		SPELL_LEARN, SPELLLEARNCOLOR, SPELLLEARNBOOSTER, NPCINTERACTION, CANVASFADE,
		ENEMY_DETECTION, INTERACTION_OBJECT, INTERACTION_NPC, END };
	enum class SHADER_PASS_UIINTANCE { DEFAULT, ALPHABLEND, UVALPHABLEND, MAGIC_METER, SPELL_LIST, EESSENTIAL_SPELL_SOLT, EESSENTIAL_SPELL, COLOR, SPELL_HOVER, SPELL_SLOT_EFFECT, SPELL_SLOT, SPELL_LOCK, QUEST_SLOT, END };

	enum class SHADER_PASS_NPC_PBR_ANIM {
		EYELASH_DAOTHV_ToSRO, TEETH_SRXO_ToSRO, EYE_DN_ToSRO, EYE_OCC, FACIAL_HAIR_DAOTHV_ToSRO, HEAD_HAIR_DAOTHV_ToSRO, HEADwtHAND_DSRXON_ToSRO, LOWER_DSRON_ToSRO, UPPER_DMRON_ToMRO, GLASSES_DMRON_ToMRO, EmissiveMetalness_DENMRO_ToMRO, MI_ClothSim_DSEN_ToSRO, MI_Troll_Club_DAENMROSRXO_To
		, OUTLINE_READ, TEETH_SRXO_ToSRO__OUTLINE_WRITE, EYE_DN_ToSRO__OUTLINE_WRITE, HEADwtHAND_DSRXON_ToSRO__OUTLINE_WRITE, UPPER_DMRON_ToMRO__OUTLINE_WRITE, EmissiveMetalness_DENMRO_ToMRO__OUTLINE_WRITE, MI_ClothSim_DSEN_ToSRO__OUTLINE_WRITE
		, END
	};
	enum class UI_STATE { GAMEPLAYER, SPELL, QUEST, INVENTORY, SPELLLNEARN, END };

	enum class QUESTTYPE { MAIN, SUB, END };
	enum class QUESTSTATE {NONE, ACCEPTED, CLEARED, END };

	enum class EFFECT_TYPE { EFFECT, TRAIL, END };

	enum class SKILL_TYPE {
		/* 마법 */
		ARRESTO_MOMENTUM, GLACIUS, LEVIOSO, TRANSFORMATION,							// 노란색
		ACCIO, DEPULSO, DESCENDO, FLIPENDO,										// 보라색
		CONFRINGO, DIFFINDO, EXPELLIARMUS, BOMBARDA, INCENDIO,					// 빨간색
		DISILLUSIONMENT, LUMOS, REPARO, WINGARDIUM_LEVIOSA,						// 하늘색
		CONJURING_SPELL, ALTERING_SPELL, EVANESCO,								// 연녹색
		AVADAKEDAVRA, CRUCIO, IMPERIO,											// 진녹색
		BEAST_PETTING_BRUSH, BEAST_FEED, NAB_SACK,								// 하늘색
		JAP, REVELIO, PROTEGO, STUPEFY,											// 검은색
		ANCIENT_MAGIC_THROW, ANCIENT_MAGIC, ALOHOMORA, PETRIFICUS_TOTALUS, LIGHTNING,

		/* PROPS */
		BOX_SPLESH, CHAIL_SPLESH , BARRAL_SPLASH,
		
		/*상태 이펙트*/
		STUN, BLINK,

		/*스크린 이펙트*/
		SCREEN_WIND,

		/*사이드*/
		JAP_SIDE, BOMBARDA_SIDE, DESCENDO_SIDE, LEVIOSO_SIDE, WAND_END, LIGHTNING_SIDE, TRANSFORMATION_SIDE, AVADAKEDAVRA_SIDE, 

		/*트롤*/
		TROLL_ATTACK, TROLL_RUSH_HIT, TROLL_NOMAL_SMOKE, GOBLIN_PROTEGO,
		
		/*고블린*/
		GOBLIN_ATTACK, GOBILN_TELEPORT,

		/*고블린 메이지*/
		GOBLIN_MAGE_ATTACK , GOBLIN_MAGE_DOWN , GOBLIN_MAGE_SIDE,

		/*란록*/

		RANROK_FIREBALL,

		END
	};

	enum class BLOOM_TYPE { NONE, BASIC, MULTIPLY, END };

	enum class DAMAGE_TYPE { NOMAL, CRITICLA };

	enum class KEYINPUT
	{
		INPUT_1 = 1, INPUT_2, INPUT_3, INPUT_4,
		INPUT_T, INPUT_G, INPUT_X, INPUT_Z, INPUT_ESPACE,
		INPUT_TAB,
		DIM_RBUTTON_UP, DIM_RBUTTON_DOWN,
		END
	};

	enum class ELEMENT_INTERACTABLE_ID { BARREL, BOX, TABLE, CHAIR, END };
}


namespace Client {
	enum class COLLIDABLEOBJECT_KIND {
		NOT_DEFINE,
		PLAYER,
		MONSTER,
		HOSTILE_HITBOX,
		ALLY_HITBOX,
		NEUTRAL_HITBOX,
		ENVIRONMENT,
		NPC,
		ITEM,
		TRIGGERBOX,
		REGION,
		NOCOLLIDE,
		END,
	};
}
