#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, INTRO, GAMEPLAY, FIELD, RESTART, END };
	enum class MAPOBJECT_TYPE { CONTAINER, ELEMENT_STATIC, ELEMENT_INTERACT };
	enum class MAPOBJECT_RENDER_TYPE { NORMAL, DECAL, GLASS };

	enum class SHADER_PASS_ANIM { DEFAULT, SHADOW, CAPTURE, BLUR, HAIR, EYELASH, OUTLINE_WRITE, OUTLINE_READ, END };
	enum class SHADER_PASS_MESH { DEFAULT, SHADOW, SKYBOX, ALPHABLEND, EFFECT_ALPHABLEND, EFFECT_BLEND, EFFECT_ALPHABLEND_CULL, EFFECT_BLEND_CULL, CAPTURE, BLUR, EFFECT_ALPHABLEND_UVMOVE, MAPTOOL, GLASS, OUTLINE_WRITE, OUTLINE_READ, BLOOM, END };
	enum class SHADER_PASS_NORTEX { DEFAULT, TERRAIN, ENV_TERRAIN_ANISO, SHADOW, END };
	enum class SHADER_PASS_PARTICLE { EXPLOSION, END };
	enum class SHADER_PASS_POSTEX { DEFAULT, SCISSOR, UI, UVMOVE, TRAIL, TRAIL_BLEND, TRAILWB_FOR_BLEND, TRAIL_BLUR, TRAIL_BLOOM, END };
	enum class SHADER_PASS_INSTANCE_MODEL { DEFAULT, NON_NOMALMAP, BLUR, WEIGHTBLEND, NON_WORLD, NON_WORLD_BLUR, BLEND, BLEND_NOWORLD, BLOOM, BLOOM_NOWORLD, BLUR_NO_EMMISVE, BLUR_NO_WORLD_NO_EMISSIVE, WEIGHTBLEND_FOR_BLEND, END };
	enum class SHADER_PASS_UIEDITOR { DEFAULT, LOGO, LOGO_TEXT, LOGO_GLOW, ALPHABLEND, CLAMP, CURSOR, LODING, HOLD_ROTATION, MISSION, QUESTYPE, UVMULT, NINECLICE, ROTATION, SLOT, TYPE, HPBAR, MAGIC_METER, MAGIC_ICON, REMOVEUV, REVELIO, POTION, MAGIC_ITEM, SPELL_PREVIEW, SPELL_HEADER, SPELL_HEADER_LINE, SPELL_DRAG, CAMERA_LOCKON, LODING_SCREEN, ENEMY_HPBAR, END };
	enum class SHADER_PASS_UIINTANCE { DEFAULT, ALPHABLEND, UVALPHABLEND, MAGIC_METER, SPELL_LIST, EESSENTIAL_SPELL_SOLT, EESSENTIAL_SPELL, COLOR, SPELL_HOVER, SPELL_SLOT_EFFECT, SPELL_SLOT, END };

	enum class UI_STATE { GAMEPLAYER, SPELL, POTION, INVENTORY, END };

	enum class EFFECT_TYPE { EFFECT, TRAIL, END };

	enum class SKILL_TYPE {
		ARRESTO_MOMENTUM, GLACIUS, LEVIOSO, TRANSFORM,							// 노란색
		ACCIO, DEPULSO, DESCENDO, FLIPENDO,										// 보라색
		CONFRINGO, DIFFINDO, EXPELLIARMUS, BOMBARDA, INCENDIO,					// 빨간색
		DISILLUSIONMENT, LUMOS, REPARO, WINGARDIUM_LEVIOSA,						// 하늘색
		CONJURING_SPELL, ALTERING_SPELL, EVANESCO,								// 연녹색
		AVADA_KEDAVRA, CRUCIO, IMPERIO,											// 진녹색
		BEAST_PETTING_BRUSH, BEAST_FEED, NAB_SACK,								// 하늘색
		JAP, REVELIO, PROTEGO, STUPEFY,											// 검은색
		ANCIENT_MAGIC_THROW, ANCIENT_MAGIC, ALOHOMORA, PETRIFICUS_TOTALUS,
		JAP_SIDE, BOMBARDA_SIDE, DESCENDO_SIDE, LEVIOSO_SIDE, END
	};

	enum class BLOOM_TYPE { NONE, BASIC, MULTIPLY, END };

	enum class KEYINPUT
	{
		INPUT_1 = 1, INPUT_2, INPUT_3, INPUT_4,
		INPUT_T, INPUT_G,
		INPUT_TAB,
		DIM_RBUTTON_UP, DIM_RBUTTON_DOWN,
		END
	};
	enum class MOUSEINPUT { LBUTTON, RBUTTON };
	enum class ELEMENT_INTERACTABLE_ID { BARREL, BOX, TABLE, END };
}


namespace Client {
	enum class COLLIDABLEOBJECT_KIND {
		NOT_DEFINE,
		PLAYER,
		MONSTER,
		HOSTILE_HITBOX,
		ALLY_HITBOX,
		NEUTRAL_HITBOX,
		ENVIRONMENT,
		NPC,
		ITEM,
		TRIGGERBOX,
		REGION,
		NOCOLLIDE,
		END,
	};
}
