#pragma once
#include "Client_Define.h"

NS_BEGIN(Client)

enum class PLAYER_MESH_ORDER {
	HEAD_EYE_OCC,
	HEAD_FACE,
	HEAD_TEETH,
	HEAD_EYELASH,
	HEAD_EYES,
	BODY_ARMS,
	HAIR_MAIN,
	HAIR_MAIN_CLOTH,
	LOWER,
	SHOES,
	UPPER,
	HAIR_SUB,
	HAIR_SUB_CLOTH,
	ROBE_SKIRT,
	ROBE_FUR,
	ROBE_CLOTH,
	END
};

static const _char* PLAYER_JOINT_BONE_NAMES[16] = {
			"RightUpLeg_Cloth"
		,	"RightLeg_Cloth"
		,	"RightDownLeg_Cloth"

		,	"LeftUpLeg_Cloth"
		,	"LeftLeg_Cloth"
		,	"LeftDownLeg_Cloth"

		,	"TailUp_Cloth"
		,	"Tail_Cloth"
		,	"TailLeftDown_Cloth"
		,	"TailRightDown_Cloth"

		,	"RightSideUpLeg_Cloth"
		,	"RightSideLeg_Cloth"
		,	"RightDownSideLeg_Cloth"

		,	"LeftSideUpLeg_Cloth"
		,	"LeftSideLeg_Cloth"
		,	"LeftDownSideLeg_Cloth"
};

enum class PLAYER_JOINT_BONE_ORDER {
		RIGHTUP
	,	RIGHT
	,	RIGHTDOWN

	,	LEFTUP
	,	LEFT
	,	LEFTDOWN

	,	TAILUP
	,	TAIL
	,	TAILLEFTDOWN
	,	TAILRIGHTDOWN

	,	RIGHTSIDEUP
	,	RIGHTSIDE
	,	RIGHTDOWNSIDE

	,	LEFTSIDEUP
	,	LEFTSIDE
	,	LEFTDOWNSIDE

	,	END
};

enum class PLAYER_JOINT_ORDER {
#pragma region ORIGIN_TO_UP
	ORIGIN_TO_RUP_START
	, ORIGIN_TO_RUP_END

	, ORIGIN_TO_TUP_START
	, ORIGIN_TO_TUP_END

	, ORIGIN_TO_LUP_START
	, ORIGIN_TO_LUP_END

	, ORIGIN_TO_RSIDEUP_START
	, ORIGIN_TO_RSIDEUP_END
	
	, ORIGIN_TO_LSIDEUP_START
	, ORIGIN_TO_LSIDEUP_END
#pragma endregion
#pragma region UP_TO_MIDDLE
	, RUP_TO_RMIDDLE_START
	, RUP_TO_RMIDDLE_END

	, TUP_TO_TMIDDLE_START
	, TUP_TO_TMIDDLE_END

	, LUP_TO_LMIDDLE_START
	, LUP_TO_LMIDDLE_END

	, RSIDEUP_TO_RSIDE_START
	, RSIDEUP_TO_RSIDE_END

	, LSIDEUP_TO_LSIDE_START
	, LSIDEUP_TO_LSIDE_END
#pragma endregion
#pragma region MIDDLE_TO_BOTTOM
	, RMIDDLE_TO_RR_START
	, RMIDDLE_TO_RR_END

	, TMIDDLE_TO_TR_START
	, TMIDDLE_TO_TR_END

	, TMIDDLE_TO_TL_START
	, TMIDDLE_TO_TL_END

	, LMIDDLE_TO_LL_START
	, LMIDDLE_TO_LL_END

	, RSIDE_TO_R_START
	, RSIDE_TO_R_END

	, LSIDE_TO_L_START
	, LSIDE_TO_L_END
#pragma endregion
#pragma region UP_HORIZONTAL
	, UP_R_RS_START
	, UP_R_RS_END
	, UP_RS_T_START
	, UP_RS_T_END
	, UP_T_LS_START
	, UP_T_LS_END
	, UP_LS_L_START
	, UP_LS_L_END
#pragma endregion
#pragma region MIDDLE_HORIZONTAL
	, MIDDLE_R_RS_START
	, MIDDLE_R_RS_END
	, MIDDLE_RS_T_START
	, MIDDLE_RS_T_END
	, MIDDLE_T_LS_START
	, MIDDLE_T_LS_END
	, MIDDLE_LS_L_START
	, MIDDLE_LS_L_END
#pragma endregion
#pragma region DOWN_HORIZONTAL
	, DOWN_R_RS_START
	, DOWN_R_RS_END
	, DOWN_RS_T_START
	, DOWN_RS_T_END
	, DOWN_T_LS_START
	, DOWN_T_LS_END
	, DOWN_LS_L_START
	, DOWN_LS_L_END
#pragma endregion
	, END
};

enum class PLAYER_JOINT_ROUTE_ORDER {
	ORIGIN_TO_RUP
	, ORIGIN_TO_TUP
	, ORIGIN_TO_LUP
	, ORIGIN_TO_RSIDEUP
	, ORIGIN_TO_LSIDEUP

	, RUP_TO_RMIDDLE
	, TUP_TO_TMIDDLE
	, LUP_TO_LMIDDLE

	, RSIDEUP_TO_RSIDE
	, LSIDEUP_TO_LSIDE

	, RMIDDLE_TO_RR
	, TMIDDLE_TO_TR
	, TMIDDLE_TO_TL
	, LMIDDLE_TO_LL

	, RSIDE_TO_R
	, LSIDE_TO_L

	, END
};


NS_END
